
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OwingSmsSend` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model OwingSmsSend
 * 
 */
export type OwingSmsSendModel = runtime.Types.Result.DefaultSelection<Prisma.$OwingSmsSendPayload>

export type AggregateOwingSmsSend = {
  _count: OwingSmsSendCountAggregateOutputType | null
  _min: OwingSmsSendMinAggregateOutputType | null
  _max: OwingSmsSendMaxAggregateOutputType | null
}

export type OwingSmsSendMinAggregateOutputType = {
  enrolment_id: string | null
  term_id: string | null
  template_id: string | null
  phone_number: string | null
  sent_at: Date | null
}

export type OwingSmsSendMaxAggregateOutputType = {
  enrolment_id: string | null
  term_id: string | null
  template_id: string | null
  phone_number: string | null
  sent_at: Date | null
}

export type OwingSmsSendCountAggregateOutputType = {
  enrolment_id: number
  term_id: number
  template_id: number
  phone_number: number
  sent_at: number
  _all: number
}


export type OwingSmsSendMinAggregateInputType = {
  enrolment_id?: true
  term_id?: true
  template_id?: true
  phone_number?: true
  sent_at?: true
}

export type OwingSmsSendMaxAggregateInputType = {
  enrolment_id?: true
  term_id?: true
  template_id?: true
  phone_number?: true
  sent_at?: true
}

export type OwingSmsSendCountAggregateInputType = {
  enrolment_id?: true
  term_id?: true
  template_id?: true
  phone_number?: true
  sent_at?: true
  _all?: true
}

export type OwingSmsSendAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OwingSmsSend to aggregate.
   */
  where?: Prisma.OwingSmsSendWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwingSmsSends to fetch.
   */
  orderBy?: Prisma.OwingSmsSendOrderByWithRelationInput | Prisma.OwingSmsSendOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OwingSmsSendWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwingSmsSends from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwingSmsSends.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OwingSmsSends
  **/
  _count?: true | OwingSmsSendCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OwingSmsSendMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OwingSmsSendMaxAggregateInputType
}

export type GetOwingSmsSendAggregateType<T extends OwingSmsSendAggregateArgs> = {
      [P in keyof T & keyof AggregateOwingSmsSend]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOwingSmsSend[P]>
    : Prisma.GetScalarType<T[P], AggregateOwingSmsSend[P]>
}




export type OwingSmsSendGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OwingSmsSendWhereInput
  orderBy?: Prisma.OwingSmsSendOrderByWithAggregationInput | Prisma.OwingSmsSendOrderByWithAggregationInput[]
  by: Prisma.OwingSmsSendScalarFieldEnum[] | Prisma.OwingSmsSendScalarFieldEnum
  having?: Prisma.OwingSmsSendScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OwingSmsSendCountAggregateInputType | true
  _min?: OwingSmsSendMinAggregateInputType
  _max?: OwingSmsSendMaxAggregateInputType
}

export type OwingSmsSendGroupByOutputType = {
  enrolment_id: string
  term_id: string
  template_id: string
  phone_number: string
  sent_at: Date
  _count: OwingSmsSendCountAggregateOutputType | null
  _min: OwingSmsSendMinAggregateOutputType | null
  _max: OwingSmsSendMaxAggregateOutputType | null
}

type GetOwingSmsSendGroupByPayload<T extends OwingSmsSendGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OwingSmsSendGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OwingSmsSendGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OwingSmsSendGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OwingSmsSendGroupByOutputType[P]>
      }
    >
  >



export type OwingSmsSendWhereInput = {
  AND?: Prisma.OwingSmsSendWhereInput | Prisma.OwingSmsSendWhereInput[]
  OR?: Prisma.OwingSmsSendWhereInput[]
  NOT?: Prisma.OwingSmsSendWhereInput | Prisma.OwingSmsSendWhereInput[]
  enrolment_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  term_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  template_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  phone_number?: Prisma.StringFilter<"OwingSmsSend"> | string
  sent_at?: Prisma.DateTimeFilter<"OwingSmsSend"> | Date | string
  enrolment?: Prisma.XOR<Prisma.EnrolmentScalarRelationFilter, Prisma.EnrolmentWhereInput>
  template?: Prisma.XOR<Prisma.SmsTemplateScalarRelationFilter, Prisma.SmsTemplateWhereInput>
}

export type OwingSmsSendOrderByWithRelationInput = {
  enrolment_id?: Prisma.SortOrder
  term_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
  enrolment?: Prisma.EnrolmentOrderByWithRelationInput
  template?: Prisma.SmsTemplateOrderByWithRelationInput
}

export type OwingSmsSendWhereUniqueInput = Prisma.AtLeast<{
  enrolment_id_term_id_template_id_phone_number?: Prisma.OwingSmsSendEnrolment_idTerm_idTemplate_idPhone_numberCompoundUniqueInput
  AND?: Prisma.OwingSmsSendWhereInput | Prisma.OwingSmsSendWhereInput[]
  OR?: Prisma.OwingSmsSendWhereInput[]
  NOT?: Prisma.OwingSmsSendWhereInput | Prisma.OwingSmsSendWhereInput[]
  enrolment_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  term_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  template_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  phone_number?: Prisma.StringFilter<"OwingSmsSend"> | string
  sent_at?: Prisma.DateTimeFilter<"OwingSmsSend"> | Date | string
  enrolment?: Prisma.XOR<Prisma.EnrolmentScalarRelationFilter, Prisma.EnrolmentWhereInput>
  template?: Prisma.XOR<Prisma.SmsTemplateScalarRelationFilter, Prisma.SmsTemplateWhereInput>
}, "enrolment_id_term_id_template_id_phone_number">

export type OwingSmsSendOrderByWithAggregationInput = {
  enrolment_id?: Prisma.SortOrder
  term_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
  _count?: Prisma.OwingSmsSendCountOrderByAggregateInput
  _max?: Prisma.OwingSmsSendMaxOrderByAggregateInput
  _min?: Prisma.OwingSmsSendMinOrderByAggregateInput
}

export type OwingSmsSendScalarWhereWithAggregatesInput = {
  AND?: Prisma.OwingSmsSendScalarWhereWithAggregatesInput | Prisma.OwingSmsSendScalarWhereWithAggregatesInput[]
  OR?: Prisma.OwingSmsSendScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OwingSmsSendScalarWhereWithAggregatesInput | Prisma.OwingSmsSendScalarWhereWithAggregatesInput[]
  enrolment_id?: Prisma.UuidWithAggregatesFilter<"OwingSmsSend"> | string
  term_id?: Prisma.UuidWithAggregatesFilter<"OwingSmsSend"> | string
  template_id?: Prisma.UuidWithAggregatesFilter<"OwingSmsSend"> | string
  phone_number?: Prisma.StringWithAggregatesFilter<"OwingSmsSend"> | string
  sent_at?: Prisma.DateTimeWithAggregatesFilter<"OwingSmsSend"> | Date | string
}

export type OwingSmsSendCreateInput = {
  term_id: string
  phone_number: string
  sent_at?: Date | string
  enrolment: Prisma.EnrolmentCreateNestedOneWithoutSmsSendsInput
  template: Prisma.SmsTemplateCreateNestedOneWithoutOwingSendsInput
}

export type OwingSmsSendUncheckedCreateInput = {
  enrolment_id: string
  term_id: string
  template_id: string
  phone_number: string
  sent_at?: Date | string
}

export type OwingSmsSendUpdateInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrolment?: Prisma.EnrolmentUpdateOneRequiredWithoutSmsSendsNestedInput
  template?: Prisma.SmsTemplateUpdateOneRequiredWithoutOwingSendsNestedInput
}

export type OwingSmsSendUncheckedUpdateInput = {
  enrolment_id?: Prisma.StringFieldUpdateOperationsInput | string
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OwingSmsSendCreateManyInput = {
  enrolment_id: string
  term_id: string
  template_id: string
  phone_number: string
  sent_at?: Date | string
}

export type OwingSmsSendUpdateManyMutationInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OwingSmsSendUncheckedUpdateManyInput = {
  enrolment_id?: Prisma.StringFieldUpdateOperationsInput | string
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OwingSmsSendListRelationFilter = {
  every?: Prisma.OwingSmsSendWhereInput
  some?: Prisma.OwingSmsSendWhereInput
  none?: Prisma.OwingSmsSendWhereInput
}

export type OwingSmsSendOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OwingSmsSendEnrolment_idTerm_idTemplate_idPhone_numberCompoundUniqueInput = {
  enrolment_id: string
  term_id: string
  template_id: string
  phone_number: string
}

export type OwingSmsSendCountOrderByAggregateInput = {
  enrolment_id?: Prisma.SortOrder
  term_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
}

export type OwingSmsSendMaxOrderByAggregateInput = {
  enrolment_id?: Prisma.SortOrder
  term_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
}

export type OwingSmsSendMinOrderByAggregateInput = {
  enrolment_id?: Prisma.SortOrder
  term_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  phone_number?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
}

export type OwingSmsSendCreateNestedManyWithoutEnrolmentInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput> | Prisma.OwingSmsSendCreateWithoutEnrolmentInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput | Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput[]
  createMany?: Prisma.OwingSmsSendCreateManyEnrolmentInputEnvelope
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
}

export type OwingSmsSendUncheckedCreateNestedManyWithoutEnrolmentInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput> | Prisma.OwingSmsSendCreateWithoutEnrolmentInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput | Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput[]
  createMany?: Prisma.OwingSmsSendCreateManyEnrolmentInputEnvelope
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
}

export type OwingSmsSendUpdateManyWithoutEnrolmentNestedInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput> | Prisma.OwingSmsSendCreateWithoutEnrolmentInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput | Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput[]
  upsert?: Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutEnrolmentInput | Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutEnrolmentInput[]
  createMany?: Prisma.OwingSmsSendCreateManyEnrolmentInputEnvelope
  set?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  disconnect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  delete?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  update?: Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutEnrolmentInput | Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutEnrolmentInput[]
  updateMany?: Prisma.OwingSmsSendUpdateManyWithWhereWithoutEnrolmentInput | Prisma.OwingSmsSendUpdateManyWithWhereWithoutEnrolmentInput[]
  deleteMany?: Prisma.OwingSmsSendScalarWhereInput | Prisma.OwingSmsSendScalarWhereInput[]
}

export type OwingSmsSendUncheckedUpdateManyWithoutEnrolmentNestedInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput> | Prisma.OwingSmsSendCreateWithoutEnrolmentInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput | Prisma.OwingSmsSendCreateOrConnectWithoutEnrolmentInput[]
  upsert?: Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutEnrolmentInput | Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutEnrolmentInput[]
  createMany?: Prisma.OwingSmsSendCreateManyEnrolmentInputEnvelope
  set?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  disconnect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  delete?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  update?: Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutEnrolmentInput | Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutEnrolmentInput[]
  updateMany?: Prisma.OwingSmsSendUpdateManyWithWhereWithoutEnrolmentInput | Prisma.OwingSmsSendUpdateManyWithWhereWithoutEnrolmentInput[]
  deleteMany?: Prisma.OwingSmsSendScalarWhereInput | Prisma.OwingSmsSendScalarWhereInput[]
}

export type OwingSmsSendCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput> | Prisma.OwingSmsSendCreateWithoutTemplateInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput | Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.OwingSmsSendCreateManyTemplateInputEnvelope
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
}

export type OwingSmsSendUncheckedCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput> | Prisma.OwingSmsSendCreateWithoutTemplateInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput | Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.OwingSmsSendCreateManyTemplateInputEnvelope
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
}

export type OwingSmsSendUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput> | Prisma.OwingSmsSendCreateWithoutTemplateInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput | Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutTemplateInput | Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.OwingSmsSendCreateManyTemplateInputEnvelope
  set?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  disconnect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  delete?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  update?: Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutTemplateInput | Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.OwingSmsSendUpdateManyWithWhereWithoutTemplateInput | Prisma.OwingSmsSendUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.OwingSmsSendScalarWhereInput | Prisma.OwingSmsSendScalarWhereInput[]
}

export type OwingSmsSendUncheckedUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput> | Prisma.OwingSmsSendCreateWithoutTemplateInput[] | Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput | Prisma.OwingSmsSendCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutTemplateInput | Prisma.OwingSmsSendUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.OwingSmsSendCreateManyTemplateInputEnvelope
  set?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  disconnect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  delete?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  connect?: Prisma.OwingSmsSendWhereUniqueInput | Prisma.OwingSmsSendWhereUniqueInput[]
  update?: Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutTemplateInput | Prisma.OwingSmsSendUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.OwingSmsSendUpdateManyWithWhereWithoutTemplateInput | Prisma.OwingSmsSendUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.OwingSmsSendScalarWhereInput | Prisma.OwingSmsSendScalarWhereInput[]
}

export type OwingSmsSendCreateWithoutEnrolmentInput = {
  term_id: string
  phone_number: string
  sent_at?: Date | string
  template: Prisma.SmsTemplateCreateNestedOneWithoutOwingSendsInput
}

export type OwingSmsSendUncheckedCreateWithoutEnrolmentInput = {
  term_id: string
  template_id: string
  phone_number: string
  sent_at?: Date | string
}

export type OwingSmsSendCreateOrConnectWithoutEnrolmentInput = {
  where: Prisma.OwingSmsSendWhereUniqueInput
  create: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput>
}

export type OwingSmsSendCreateManyEnrolmentInputEnvelope = {
  data: Prisma.OwingSmsSendCreateManyEnrolmentInput | Prisma.OwingSmsSendCreateManyEnrolmentInput[]
  skipDuplicates?: boolean
}

export type OwingSmsSendUpsertWithWhereUniqueWithoutEnrolmentInput = {
  where: Prisma.OwingSmsSendWhereUniqueInput
  update: Prisma.XOR<Prisma.OwingSmsSendUpdateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedUpdateWithoutEnrolmentInput>
  create: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedCreateWithoutEnrolmentInput>
}

export type OwingSmsSendUpdateWithWhereUniqueWithoutEnrolmentInput = {
  where: Prisma.OwingSmsSendWhereUniqueInput
  data: Prisma.XOR<Prisma.OwingSmsSendUpdateWithoutEnrolmentInput, Prisma.OwingSmsSendUncheckedUpdateWithoutEnrolmentInput>
}

export type OwingSmsSendUpdateManyWithWhereWithoutEnrolmentInput = {
  where: Prisma.OwingSmsSendScalarWhereInput
  data: Prisma.XOR<Prisma.OwingSmsSendUpdateManyMutationInput, Prisma.OwingSmsSendUncheckedUpdateManyWithoutEnrolmentInput>
}

export type OwingSmsSendScalarWhereInput = {
  AND?: Prisma.OwingSmsSendScalarWhereInput | Prisma.OwingSmsSendScalarWhereInput[]
  OR?: Prisma.OwingSmsSendScalarWhereInput[]
  NOT?: Prisma.OwingSmsSendScalarWhereInput | Prisma.OwingSmsSendScalarWhereInput[]
  enrolment_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  term_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  template_id?: Prisma.UuidFilter<"OwingSmsSend"> | string
  phone_number?: Prisma.StringFilter<"OwingSmsSend"> | string
  sent_at?: Prisma.DateTimeFilter<"OwingSmsSend"> | Date | string
}

export type OwingSmsSendCreateWithoutTemplateInput = {
  term_id: string
  phone_number: string
  sent_at?: Date | string
  enrolment: Prisma.EnrolmentCreateNestedOneWithoutSmsSendsInput
}

export type OwingSmsSendUncheckedCreateWithoutTemplateInput = {
  enrolment_id: string
  term_id: string
  phone_number: string
  sent_at?: Date | string
}

export type OwingSmsSendCreateOrConnectWithoutTemplateInput = {
  where: Prisma.OwingSmsSendWhereUniqueInput
  create: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput>
}

export type OwingSmsSendCreateManyTemplateInputEnvelope = {
  data: Prisma.OwingSmsSendCreateManyTemplateInput | Prisma.OwingSmsSendCreateManyTemplateInput[]
  skipDuplicates?: boolean
}

export type OwingSmsSendUpsertWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.OwingSmsSendWhereUniqueInput
  update: Prisma.XOR<Prisma.OwingSmsSendUpdateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedUpdateWithoutTemplateInput>
  create: Prisma.XOR<Prisma.OwingSmsSendCreateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedCreateWithoutTemplateInput>
}

export type OwingSmsSendUpdateWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.OwingSmsSendWhereUniqueInput
  data: Prisma.XOR<Prisma.OwingSmsSendUpdateWithoutTemplateInput, Prisma.OwingSmsSendUncheckedUpdateWithoutTemplateInput>
}

export type OwingSmsSendUpdateManyWithWhereWithoutTemplateInput = {
  where: Prisma.OwingSmsSendScalarWhereInput
  data: Prisma.XOR<Prisma.OwingSmsSendUpdateManyMutationInput, Prisma.OwingSmsSendUncheckedUpdateManyWithoutTemplateInput>
}

export type OwingSmsSendCreateManyEnrolmentInput = {
  term_id: string
  template_id: string
  phone_number: string
  sent_at?: Date | string
}

export type OwingSmsSendUpdateWithoutEnrolmentInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  template?: Prisma.SmsTemplateUpdateOneRequiredWithoutOwingSendsNestedInput
}

export type OwingSmsSendUncheckedUpdateWithoutEnrolmentInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OwingSmsSendUncheckedUpdateManyWithoutEnrolmentInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OwingSmsSendCreateManyTemplateInput = {
  enrolment_id: string
  term_id: string
  phone_number: string
  sent_at?: Date | string
}

export type OwingSmsSendUpdateWithoutTemplateInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrolment?: Prisma.EnrolmentUpdateOneRequiredWithoutSmsSendsNestedInput
}

export type OwingSmsSendUncheckedUpdateWithoutTemplateInput = {
  enrolment_id?: Prisma.StringFieldUpdateOperationsInput | string
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OwingSmsSendUncheckedUpdateManyWithoutTemplateInput = {
  enrolment_id?: Prisma.StringFieldUpdateOperationsInput | string
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  phone_number?: Prisma.StringFieldUpdateOperationsInput | string
  sent_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OwingSmsSendSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  enrolment_id?: boolean
  term_id?: boolean
  template_id?: boolean
  phone_number?: boolean
  sent_at?: boolean
  enrolment?: boolean | Prisma.EnrolmentDefaultArgs<ExtArgs>
  template?: boolean | Prisma.SmsTemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["owingSmsSend"]>

export type OwingSmsSendSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  enrolment_id?: boolean
  term_id?: boolean
  template_id?: boolean
  phone_number?: boolean
  sent_at?: boolean
  enrolment?: boolean | Prisma.EnrolmentDefaultArgs<ExtArgs>
  template?: boolean | Prisma.SmsTemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["owingSmsSend"]>

export type OwingSmsSendSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  enrolment_id?: boolean
  term_id?: boolean
  template_id?: boolean
  phone_number?: boolean
  sent_at?: boolean
  enrolment?: boolean | Prisma.EnrolmentDefaultArgs<ExtArgs>
  template?: boolean | Prisma.SmsTemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["owingSmsSend"]>

export type OwingSmsSendSelectScalar = {
  enrolment_id?: boolean
  term_id?: boolean
  template_id?: boolean
  phone_number?: boolean
  sent_at?: boolean
}

export type OwingSmsSendOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"enrolment_id" | "term_id" | "template_id" | "phone_number" | "sent_at", ExtArgs["result"]["owingSmsSend"]>
export type OwingSmsSendInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  enrolment?: boolean | Prisma.EnrolmentDefaultArgs<ExtArgs>
  template?: boolean | Prisma.SmsTemplateDefaultArgs<ExtArgs>
}
export type OwingSmsSendIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  enrolment?: boolean | Prisma.EnrolmentDefaultArgs<ExtArgs>
  template?: boolean | Prisma.SmsTemplateDefaultArgs<ExtArgs>
}
export type OwingSmsSendIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  enrolment?: boolean | Prisma.EnrolmentDefaultArgs<ExtArgs>
  template?: boolean | Prisma.SmsTemplateDefaultArgs<ExtArgs>
}

export type $OwingSmsSendPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OwingSmsSend"
  objects: {
    enrolment: Prisma.$EnrolmentPayload<ExtArgs>
    template: Prisma.$SmsTemplatePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    enrolment_id: string
    term_id: string
    template_id: string
    phone_number: string
    sent_at: Date
  }, ExtArgs["result"]["owingSmsSend"]>
  composites: {}
}

export type OwingSmsSendGetPayload<S extends boolean | null | undefined | OwingSmsSendDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload, S>

export type OwingSmsSendCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OwingSmsSendFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OwingSmsSendCountAggregateInputType | true
  }

export interface OwingSmsSendDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OwingSmsSend'], meta: { name: 'OwingSmsSend' } }
  /**
   * Find zero or one OwingSmsSend that matches the filter.
   * @param {OwingSmsSendFindUniqueArgs} args - Arguments to find a OwingSmsSend
   * @example
   * // Get one OwingSmsSend
   * const owingSmsSend = await prisma.owingSmsSend.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OwingSmsSendFindUniqueArgs>(args: Prisma.SelectSubset<T, OwingSmsSendFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OwingSmsSend that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OwingSmsSendFindUniqueOrThrowArgs} args - Arguments to find a OwingSmsSend
   * @example
   * // Get one OwingSmsSend
   * const owingSmsSend = await prisma.owingSmsSend.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OwingSmsSendFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OwingSmsSendFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OwingSmsSend that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwingSmsSendFindFirstArgs} args - Arguments to find a OwingSmsSend
   * @example
   * // Get one OwingSmsSend
   * const owingSmsSend = await prisma.owingSmsSend.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OwingSmsSendFindFirstArgs>(args?: Prisma.SelectSubset<T, OwingSmsSendFindFirstArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OwingSmsSend that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwingSmsSendFindFirstOrThrowArgs} args - Arguments to find a OwingSmsSend
   * @example
   * // Get one OwingSmsSend
   * const owingSmsSend = await prisma.owingSmsSend.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OwingSmsSendFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OwingSmsSendFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OwingSmsSends that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwingSmsSendFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OwingSmsSends
   * const owingSmsSends = await prisma.owingSmsSend.findMany()
   * 
   * // Get first 10 OwingSmsSends
   * const owingSmsSends = await prisma.owingSmsSend.findMany({ take: 10 })
   * 
   * // Only select the `enrolment_id`
   * const owingSmsSendWithEnrolment_idOnly = await prisma.owingSmsSend.findMany({ select: { enrolment_id: true } })
   * 
   */
  findMany<T extends OwingSmsSendFindManyArgs>(args?: Prisma.SelectSubset<T, OwingSmsSendFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OwingSmsSend.
   * @param {OwingSmsSendCreateArgs} args - Arguments to create a OwingSmsSend.
   * @example
   * // Create one OwingSmsSend
   * const OwingSmsSend = await prisma.owingSmsSend.create({
   *   data: {
   *     // ... data to create a OwingSmsSend
   *   }
   * })
   * 
   */
  create<T extends OwingSmsSendCreateArgs>(args: Prisma.SelectSubset<T, OwingSmsSendCreateArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OwingSmsSends.
   * @param {OwingSmsSendCreateManyArgs} args - Arguments to create many OwingSmsSends.
   * @example
   * // Create many OwingSmsSends
   * const owingSmsSend = await prisma.owingSmsSend.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OwingSmsSendCreateManyArgs>(args?: Prisma.SelectSubset<T, OwingSmsSendCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OwingSmsSends and returns the data saved in the database.
   * @param {OwingSmsSendCreateManyAndReturnArgs} args - Arguments to create many OwingSmsSends.
   * @example
   * // Create many OwingSmsSends
   * const owingSmsSend = await prisma.owingSmsSend.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OwingSmsSends and only return the `enrolment_id`
   * const owingSmsSendWithEnrolment_idOnly = await prisma.owingSmsSend.createManyAndReturn({
   *   select: { enrolment_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OwingSmsSendCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OwingSmsSendCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OwingSmsSend.
   * @param {OwingSmsSendDeleteArgs} args - Arguments to delete one OwingSmsSend.
   * @example
   * // Delete one OwingSmsSend
   * const OwingSmsSend = await prisma.owingSmsSend.delete({
   *   where: {
   *     // ... filter to delete one OwingSmsSend
   *   }
   * })
   * 
   */
  delete<T extends OwingSmsSendDeleteArgs>(args: Prisma.SelectSubset<T, OwingSmsSendDeleteArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OwingSmsSend.
   * @param {OwingSmsSendUpdateArgs} args - Arguments to update one OwingSmsSend.
   * @example
   * // Update one OwingSmsSend
   * const owingSmsSend = await prisma.owingSmsSend.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OwingSmsSendUpdateArgs>(args: Prisma.SelectSubset<T, OwingSmsSendUpdateArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OwingSmsSends.
   * @param {OwingSmsSendDeleteManyArgs} args - Arguments to filter OwingSmsSends to delete.
   * @example
   * // Delete a few OwingSmsSends
   * const { count } = await prisma.owingSmsSend.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OwingSmsSendDeleteManyArgs>(args?: Prisma.SelectSubset<T, OwingSmsSendDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OwingSmsSends.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwingSmsSendUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OwingSmsSends
   * const owingSmsSend = await prisma.owingSmsSend.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OwingSmsSendUpdateManyArgs>(args: Prisma.SelectSubset<T, OwingSmsSendUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OwingSmsSends and returns the data updated in the database.
   * @param {OwingSmsSendUpdateManyAndReturnArgs} args - Arguments to update many OwingSmsSends.
   * @example
   * // Update many OwingSmsSends
   * const owingSmsSend = await prisma.owingSmsSend.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OwingSmsSends and only return the `enrolment_id`
   * const owingSmsSendWithEnrolment_idOnly = await prisma.owingSmsSend.updateManyAndReturn({
   *   select: { enrolment_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OwingSmsSendUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OwingSmsSendUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OwingSmsSend.
   * @param {OwingSmsSendUpsertArgs} args - Arguments to update or create a OwingSmsSend.
   * @example
   * // Update or create a OwingSmsSend
   * const owingSmsSend = await prisma.owingSmsSend.upsert({
   *   create: {
   *     // ... data to create a OwingSmsSend
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OwingSmsSend we want to update
   *   }
   * })
   */
  upsert<T extends OwingSmsSendUpsertArgs>(args: Prisma.SelectSubset<T, OwingSmsSendUpsertArgs<ExtArgs>>): Prisma.Prisma__OwingSmsSendClient<runtime.Types.Result.GetResult<Prisma.$OwingSmsSendPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OwingSmsSends.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwingSmsSendCountArgs} args - Arguments to filter OwingSmsSends to count.
   * @example
   * // Count the number of OwingSmsSends
   * const count = await prisma.owingSmsSend.count({
   *   where: {
   *     // ... the filter for the OwingSmsSends we want to count
   *   }
   * })
  **/
  count<T extends OwingSmsSendCountArgs>(
    args?: Prisma.Subset<T, OwingSmsSendCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OwingSmsSendCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OwingSmsSend.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwingSmsSendAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OwingSmsSendAggregateArgs>(args: Prisma.Subset<T, OwingSmsSendAggregateArgs>): Prisma.PrismaPromise<GetOwingSmsSendAggregateType<T>>

  /**
   * Group by OwingSmsSend.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwingSmsSendGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OwingSmsSendGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OwingSmsSendGroupByArgs['orderBy'] }
      : { orderBy?: OwingSmsSendGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OwingSmsSendGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOwingSmsSendGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OwingSmsSend model
 */
readonly fields: OwingSmsSendFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OwingSmsSend.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OwingSmsSendClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  enrolment<T extends Prisma.EnrolmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EnrolmentDefaultArgs<ExtArgs>>): Prisma.Prisma__EnrolmentClient<runtime.Types.Result.GetResult<Prisma.$EnrolmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  template<T extends Prisma.SmsTemplateDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SmsTemplateDefaultArgs<ExtArgs>>): Prisma.Prisma__SmsTemplateClient<runtime.Types.Result.GetResult<Prisma.$SmsTemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OwingSmsSend model
 */
export interface OwingSmsSendFieldRefs {
  readonly enrolment_id: Prisma.FieldRef<"OwingSmsSend", 'String'>
  readonly term_id: Prisma.FieldRef<"OwingSmsSend", 'String'>
  readonly template_id: Prisma.FieldRef<"OwingSmsSend", 'String'>
  readonly phone_number: Prisma.FieldRef<"OwingSmsSend", 'String'>
  readonly sent_at: Prisma.FieldRef<"OwingSmsSend", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OwingSmsSend findUnique
 */
export type OwingSmsSendFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * Filter, which OwingSmsSend to fetch.
   */
  where: Prisma.OwingSmsSendWhereUniqueInput
}

/**
 * OwingSmsSend findUniqueOrThrow
 */
export type OwingSmsSendFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * Filter, which OwingSmsSend to fetch.
   */
  where: Prisma.OwingSmsSendWhereUniqueInput
}

/**
 * OwingSmsSend findFirst
 */
export type OwingSmsSendFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * Filter, which OwingSmsSend to fetch.
   */
  where?: Prisma.OwingSmsSendWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwingSmsSends to fetch.
   */
  orderBy?: Prisma.OwingSmsSendOrderByWithRelationInput | Prisma.OwingSmsSendOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OwingSmsSends.
   */
  cursor?: Prisma.OwingSmsSendWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwingSmsSends from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwingSmsSends.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OwingSmsSends.
   */
  distinct?: Prisma.OwingSmsSendScalarFieldEnum | Prisma.OwingSmsSendScalarFieldEnum[]
}

/**
 * OwingSmsSend findFirstOrThrow
 */
export type OwingSmsSendFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * Filter, which OwingSmsSend to fetch.
   */
  where?: Prisma.OwingSmsSendWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwingSmsSends to fetch.
   */
  orderBy?: Prisma.OwingSmsSendOrderByWithRelationInput | Prisma.OwingSmsSendOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OwingSmsSends.
   */
  cursor?: Prisma.OwingSmsSendWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwingSmsSends from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwingSmsSends.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OwingSmsSends.
   */
  distinct?: Prisma.OwingSmsSendScalarFieldEnum | Prisma.OwingSmsSendScalarFieldEnum[]
}

/**
 * OwingSmsSend findMany
 */
export type OwingSmsSendFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * Filter, which OwingSmsSends to fetch.
   */
  where?: Prisma.OwingSmsSendWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwingSmsSends to fetch.
   */
  orderBy?: Prisma.OwingSmsSendOrderByWithRelationInput | Prisma.OwingSmsSendOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OwingSmsSends.
   */
  cursor?: Prisma.OwingSmsSendWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwingSmsSends from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwingSmsSends.
   */
  skip?: number
  distinct?: Prisma.OwingSmsSendScalarFieldEnum | Prisma.OwingSmsSendScalarFieldEnum[]
}

/**
 * OwingSmsSend create
 */
export type OwingSmsSendCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * The data needed to create a OwingSmsSend.
   */
  data: Prisma.XOR<Prisma.OwingSmsSendCreateInput, Prisma.OwingSmsSendUncheckedCreateInput>
}

/**
 * OwingSmsSend createMany
 */
export type OwingSmsSendCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OwingSmsSends.
   */
  data: Prisma.OwingSmsSendCreateManyInput | Prisma.OwingSmsSendCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OwingSmsSend createManyAndReturn
 */
export type OwingSmsSendCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * The data used to create many OwingSmsSends.
   */
  data: Prisma.OwingSmsSendCreateManyInput | Prisma.OwingSmsSendCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OwingSmsSend update
 */
export type OwingSmsSendUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * The data needed to update a OwingSmsSend.
   */
  data: Prisma.XOR<Prisma.OwingSmsSendUpdateInput, Prisma.OwingSmsSendUncheckedUpdateInput>
  /**
   * Choose, which OwingSmsSend to update.
   */
  where: Prisma.OwingSmsSendWhereUniqueInput
}

/**
 * OwingSmsSend updateMany
 */
export type OwingSmsSendUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OwingSmsSends.
   */
  data: Prisma.XOR<Prisma.OwingSmsSendUpdateManyMutationInput, Prisma.OwingSmsSendUncheckedUpdateManyInput>
  /**
   * Filter which OwingSmsSends to update
   */
  where?: Prisma.OwingSmsSendWhereInput
  /**
   * Limit how many OwingSmsSends to update.
   */
  limit?: number
}

/**
 * OwingSmsSend updateManyAndReturn
 */
export type OwingSmsSendUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * The data used to update OwingSmsSends.
   */
  data: Prisma.XOR<Prisma.OwingSmsSendUpdateManyMutationInput, Prisma.OwingSmsSendUncheckedUpdateManyInput>
  /**
   * Filter which OwingSmsSends to update
   */
  where?: Prisma.OwingSmsSendWhereInput
  /**
   * Limit how many OwingSmsSends to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OwingSmsSend upsert
 */
export type OwingSmsSendUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * The filter to search for the OwingSmsSend to update in case it exists.
   */
  where: Prisma.OwingSmsSendWhereUniqueInput
  /**
   * In case the OwingSmsSend found by the `where` argument doesn't exist, create a new OwingSmsSend with this data.
   */
  create: Prisma.XOR<Prisma.OwingSmsSendCreateInput, Prisma.OwingSmsSendUncheckedCreateInput>
  /**
   * In case the OwingSmsSend was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OwingSmsSendUpdateInput, Prisma.OwingSmsSendUncheckedUpdateInput>
}

/**
 * OwingSmsSend delete
 */
export type OwingSmsSendDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
  /**
   * Filter which OwingSmsSend to delete.
   */
  where: Prisma.OwingSmsSendWhereUniqueInput
}

/**
 * OwingSmsSend deleteMany
 */
export type OwingSmsSendDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OwingSmsSends to delete
   */
  where?: Prisma.OwingSmsSendWhereInput
  /**
   * Limit how many OwingSmsSends to delete.
   */
  limit?: number
}

/**
 * OwingSmsSend without action
 */
export type OwingSmsSendDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwingSmsSend
   */
  select?: Prisma.OwingSmsSendSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwingSmsSend
   */
  omit?: Prisma.OwingSmsSendOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwingSmsSendInclude<ExtArgs> | null
}
