
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SubjectOffering` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SubjectOffering
 * 
 */
export type SubjectOfferingModel = runtime.Types.Result.DefaultSelection<Prisma.$SubjectOfferingPayload>

export type AggregateSubjectOffering = {
  _count: SubjectOfferingCountAggregateOutputType | null
  _avg: SubjectOfferingAvgAggregateOutputType | null
  _sum: SubjectOfferingSumAggregateOutputType | null
  _min: SubjectOfferingMinAggregateOutputType | null
  _max: SubjectOfferingMaxAggregateOutputType | null
}

export type SubjectOfferingAvgAggregateOutputType = {
  price_per_term: runtime.Decimal | null
}

export type SubjectOfferingSumAggregateOutputType = {
  price_per_term: runtime.Decimal | null
}

export type SubjectOfferingMinAggregateOutputType = {
  offering_id: string | null
  subject_id: string | null
  grade_id: string | null
  location: $Enums.Location | null
  price_per_term: runtime.Decimal | null
}

export type SubjectOfferingMaxAggregateOutputType = {
  offering_id: string | null
  subject_id: string | null
  grade_id: string | null
  location: $Enums.Location | null
  price_per_term: runtime.Decimal | null
}

export type SubjectOfferingCountAggregateOutputType = {
  offering_id: number
  subject_id: number
  grade_id: number
  location: number
  price_per_term: number
  _all: number
}


export type SubjectOfferingAvgAggregateInputType = {
  price_per_term?: true
}

export type SubjectOfferingSumAggregateInputType = {
  price_per_term?: true
}

export type SubjectOfferingMinAggregateInputType = {
  offering_id?: true
  subject_id?: true
  grade_id?: true
  location?: true
  price_per_term?: true
}

export type SubjectOfferingMaxAggregateInputType = {
  offering_id?: true
  subject_id?: true
  grade_id?: true
  location?: true
  price_per_term?: true
}

export type SubjectOfferingCountAggregateInputType = {
  offering_id?: true
  subject_id?: true
  grade_id?: true
  location?: true
  price_per_term?: true
  _all?: true
}

export type SubjectOfferingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubjectOffering to aggregate.
   */
  where?: Prisma.SubjectOfferingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubjectOfferings to fetch.
   */
  orderBy?: Prisma.SubjectOfferingOrderByWithRelationInput | Prisma.SubjectOfferingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubjectOfferingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubjectOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubjectOfferings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SubjectOfferings
  **/
  _count?: true | SubjectOfferingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SubjectOfferingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SubjectOfferingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubjectOfferingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubjectOfferingMaxAggregateInputType
}

export type GetSubjectOfferingAggregateType<T extends SubjectOfferingAggregateArgs> = {
      [P in keyof T & keyof AggregateSubjectOffering]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubjectOffering[P]>
    : Prisma.GetScalarType<T[P], AggregateSubjectOffering[P]>
}




export type SubjectOfferingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubjectOfferingWhereInput
  orderBy?: Prisma.SubjectOfferingOrderByWithAggregationInput | Prisma.SubjectOfferingOrderByWithAggregationInput[]
  by: Prisma.SubjectOfferingScalarFieldEnum[] | Prisma.SubjectOfferingScalarFieldEnum
  having?: Prisma.SubjectOfferingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubjectOfferingCountAggregateInputType | true
  _avg?: SubjectOfferingAvgAggregateInputType
  _sum?: SubjectOfferingSumAggregateInputType
  _min?: SubjectOfferingMinAggregateInputType
  _max?: SubjectOfferingMaxAggregateInputType
}

export type SubjectOfferingGroupByOutputType = {
  offering_id: string
  subject_id: string
  grade_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal
  _count: SubjectOfferingCountAggregateOutputType | null
  _avg: SubjectOfferingAvgAggregateOutputType | null
  _sum: SubjectOfferingSumAggregateOutputType | null
  _min: SubjectOfferingMinAggregateOutputType | null
  _max: SubjectOfferingMaxAggregateOutputType | null
}

type GetSubjectOfferingGroupByPayload<T extends SubjectOfferingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubjectOfferingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubjectOfferingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubjectOfferingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubjectOfferingGroupByOutputType[P]>
      }
    >
  >



export type SubjectOfferingWhereInput = {
  AND?: Prisma.SubjectOfferingWhereInput | Prisma.SubjectOfferingWhereInput[]
  OR?: Prisma.SubjectOfferingWhereInput[]
  NOT?: Prisma.SubjectOfferingWhereInput | Prisma.SubjectOfferingWhereInput[]
  offering_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  subject_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  grade_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  location?: Prisma.EnumLocationFilter<"SubjectOffering"> | $Enums.Location
  price_per_term?: Prisma.DecimalFilter<"SubjectOffering"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  subject?: Prisma.XOR<Prisma.SubjectScalarRelationFilter, Prisma.SubjectWhereInput>
  grade?: Prisma.XOR<Prisma.GradeScalarRelationFilter, Prisma.GradeWhereInput>
  classTimes?: Prisma.ClassTimeListRelationFilter
}

export type SubjectOfferingOrderByWithRelationInput = {
  offering_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
  grade_id?: Prisma.SortOrder
  location?: Prisma.SortOrder
  price_per_term?: Prisma.SortOrder
  subject?: Prisma.SubjectOrderByWithRelationInput
  grade?: Prisma.GradeOrderByWithRelationInput
  classTimes?: Prisma.ClassTimeOrderByRelationAggregateInput
}

export type SubjectOfferingWhereUniqueInput = Prisma.AtLeast<{
  offering_id?: string
  subject_id_grade_id_location?: Prisma.SubjectOfferingSubject_idGrade_idLocationCompoundUniqueInput
  AND?: Prisma.SubjectOfferingWhereInput | Prisma.SubjectOfferingWhereInput[]
  OR?: Prisma.SubjectOfferingWhereInput[]
  NOT?: Prisma.SubjectOfferingWhereInput | Prisma.SubjectOfferingWhereInput[]
  subject_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  grade_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  location?: Prisma.EnumLocationFilter<"SubjectOffering"> | $Enums.Location
  price_per_term?: Prisma.DecimalFilter<"SubjectOffering"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  subject?: Prisma.XOR<Prisma.SubjectScalarRelationFilter, Prisma.SubjectWhereInput>
  grade?: Prisma.XOR<Prisma.GradeScalarRelationFilter, Prisma.GradeWhereInput>
  classTimes?: Prisma.ClassTimeListRelationFilter
}, "offering_id" | "subject_id_grade_id_location">

export type SubjectOfferingOrderByWithAggregationInput = {
  offering_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
  grade_id?: Prisma.SortOrder
  location?: Prisma.SortOrder
  price_per_term?: Prisma.SortOrder
  _count?: Prisma.SubjectOfferingCountOrderByAggregateInput
  _avg?: Prisma.SubjectOfferingAvgOrderByAggregateInput
  _max?: Prisma.SubjectOfferingMaxOrderByAggregateInput
  _min?: Prisma.SubjectOfferingMinOrderByAggregateInput
  _sum?: Prisma.SubjectOfferingSumOrderByAggregateInput
}

export type SubjectOfferingScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubjectOfferingScalarWhereWithAggregatesInput | Prisma.SubjectOfferingScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubjectOfferingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubjectOfferingScalarWhereWithAggregatesInput | Prisma.SubjectOfferingScalarWhereWithAggregatesInput[]
  offering_id?: Prisma.UuidWithAggregatesFilter<"SubjectOffering"> | string
  subject_id?: Prisma.UuidWithAggregatesFilter<"SubjectOffering"> | string
  grade_id?: Prisma.UuidWithAggregatesFilter<"SubjectOffering"> | string
  location?: Prisma.EnumLocationWithAggregatesFilter<"SubjectOffering"> | $Enums.Location
  price_per_term?: Prisma.DecimalWithAggregatesFilter<"SubjectOffering"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingCreateInput = {
  offering_id?: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
  subject: Prisma.SubjectCreateNestedOneWithoutOfferingsInput
  grade: Prisma.GradeCreateNestedOneWithoutOfferingsInput
  classTimes?: Prisma.ClassTimeCreateNestedManyWithoutOfferingInput
}

export type SubjectOfferingUncheckedCreateInput = {
  offering_id?: string
  subject_id: string
  grade_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
  classTimes?: Prisma.ClassTimeUncheckedCreateNestedManyWithoutOfferingInput
}

export type SubjectOfferingUpdateInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subject?: Prisma.SubjectUpdateOneRequiredWithoutOfferingsNestedInput
  grade?: Prisma.GradeUpdateOneRequiredWithoutOfferingsNestedInput
  classTimes?: Prisma.ClassTimeUpdateManyWithoutOfferingNestedInput
}

export type SubjectOfferingUncheckedUpdateInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
  grade_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  classTimes?: Prisma.ClassTimeUncheckedUpdateManyWithoutOfferingNestedInput
}

export type SubjectOfferingCreateManyInput = {
  offering_id?: string
  subject_id: string
  grade_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingUpdateManyMutationInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingUncheckedUpdateManyInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
  grade_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingScalarRelationFilter = {
  is?: Prisma.SubjectOfferingWhereInput
  isNot?: Prisma.SubjectOfferingWhereInput
}

export type SubjectOfferingListRelationFilter = {
  every?: Prisma.SubjectOfferingWhereInput
  some?: Prisma.SubjectOfferingWhereInput
  none?: Prisma.SubjectOfferingWhereInput
}

export type SubjectOfferingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SubjectOfferingSubject_idGrade_idLocationCompoundUniqueInput = {
  subject_id: string
  grade_id: string
  location: $Enums.Location
}

export type SubjectOfferingCountOrderByAggregateInput = {
  offering_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
  grade_id?: Prisma.SortOrder
  location?: Prisma.SortOrder
  price_per_term?: Prisma.SortOrder
}

export type SubjectOfferingAvgOrderByAggregateInput = {
  price_per_term?: Prisma.SortOrder
}

export type SubjectOfferingMaxOrderByAggregateInput = {
  offering_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
  grade_id?: Prisma.SortOrder
  location?: Prisma.SortOrder
  price_per_term?: Prisma.SortOrder
}

export type SubjectOfferingMinOrderByAggregateInput = {
  offering_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
  grade_id?: Prisma.SortOrder
  location?: Prisma.SortOrder
  price_per_term?: Prisma.SortOrder
}

export type SubjectOfferingSumOrderByAggregateInput = {
  price_per_term?: Prisma.SortOrder
}

export type SubjectOfferingCreateNestedOneWithoutClassTimesInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutClassTimesInput, Prisma.SubjectOfferingUncheckedCreateWithoutClassTimesInput>
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutClassTimesInput
  connect?: Prisma.SubjectOfferingWhereUniqueInput
}

export type SubjectOfferingUpdateOneRequiredWithoutClassTimesNestedInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutClassTimesInput, Prisma.SubjectOfferingUncheckedCreateWithoutClassTimesInput>
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutClassTimesInput
  upsert?: Prisma.SubjectOfferingUpsertWithoutClassTimesInput
  connect?: Prisma.SubjectOfferingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubjectOfferingUpdateToOneWithWhereWithoutClassTimesInput, Prisma.SubjectOfferingUpdateWithoutClassTimesInput>, Prisma.SubjectOfferingUncheckedUpdateWithoutClassTimesInput>
}

export type SubjectOfferingCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput> | Prisma.SubjectOfferingCreateWithoutSubjectInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput | Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.SubjectOfferingCreateManySubjectInputEnvelope
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
}

export type SubjectOfferingUncheckedCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput> | Prisma.SubjectOfferingCreateWithoutSubjectInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput | Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.SubjectOfferingCreateManySubjectInputEnvelope
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
}

export type SubjectOfferingUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput> | Prisma.SubjectOfferingCreateWithoutSubjectInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput | Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutSubjectInput | Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.SubjectOfferingCreateManySubjectInputEnvelope
  set?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  disconnect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  delete?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  update?: Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutSubjectInput | Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.SubjectOfferingUpdateManyWithWhereWithoutSubjectInput | Prisma.SubjectOfferingUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.SubjectOfferingScalarWhereInput | Prisma.SubjectOfferingScalarWhereInput[]
}

export type SubjectOfferingUncheckedUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput> | Prisma.SubjectOfferingCreateWithoutSubjectInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput | Prisma.SubjectOfferingCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutSubjectInput | Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.SubjectOfferingCreateManySubjectInputEnvelope
  set?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  disconnect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  delete?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  update?: Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutSubjectInput | Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.SubjectOfferingUpdateManyWithWhereWithoutSubjectInput | Prisma.SubjectOfferingUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.SubjectOfferingScalarWhereInput | Prisma.SubjectOfferingScalarWhereInput[]
}

export type SubjectOfferingCreateNestedManyWithoutGradeInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutGradeInput, Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput> | Prisma.SubjectOfferingCreateWithoutGradeInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput | Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput[]
  createMany?: Prisma.SubjectOfferingCreateManyGradeInputEnvelope
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
}

export type SubjectOfferingUncheckedCreateNestedManyWithoutGradeInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutGradeInput, Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput> | Prisma.SubjectOfferingCreateWithoutGradeInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput | Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput[]
  createMany?: Prisma.SubjectOfferingCreateManyGradeInputEnvelope
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
}

export type SubjectOfferingUpdateManyWithoutGradeNestedInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutGradeInput, Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput> | Prisma.SubjectOfferingCreateWithoutGradeInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput | Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput[]
  upsert?: Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutGradeInput | Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutGradeInput[]
  createMany?: Prisma.SubjectOfferingCreateManyGradeInputEnvelope
  set?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  disconnect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  delete?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  update?: Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutGradeInput | Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutGradeInput[]
  updateMany?: Prisma.SubjectOfferingUpdateManyWithWhereWithoutGradeInput | Prisma.SubjectOfferingUpdateManyWithWhereWithoutGradeInput[]
  deleteMany?: Prisma.SubjectOfferingScalarWhereInput | Prisma.SubjectOfferingScalarWhereInput[]
}

export type SubjectOfferingUncheckedUpdateManyWithoutGradeNestedInput = {
  create?: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutGradeInput, Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput> | Prisma.SubjectOfferingCreateWithoutGradeInput[] | Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput[]
  connectOrCreate?: Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput | Prisma.SubjectOfferingCreateOrConnectWithoutGradeInput[]
  upsert?: Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutGradeInput | Prisma.SubjectOfferingUpsertWithWhereUniqueWithoutGradeInput[]
  createMany?: Prisma.SubjectOfferingCreateManyGradeInputEnvelope
  set?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  disconnect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  delete?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  connect?: Prisma.SubjectOfferingWhereUniqueInput | Prisma.SubjectOfferingWhereUniqueInput[]
  update?: Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutGradeInput | Prisma.SubjectOfferingUpdateWithWhereUniqueWithoutGradeInput[]
  updateMany?: Prisma.SubjectOfferingUpdateManyWithWhereWithoutGradeInput | Prisma.SubjectOfferingUpdateManyWithWhereWithoutGradeInput[]
  deleteMany?: Prisma.SubjectOfferingScalarWhereInput | Prisma.SubjectOfferingScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingCreateWithoutClassTimesInput = {
  offering_id?: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
  subject: Prisma.SubjectCreateNestedOneWithoutOfferingsInput
  grade: Prisma.GradeCreateNestedOneWithoutOfferingsInput
}

export type SubjectOfferingUncheckedCreateWithoutClassTimesInput = {
  offering_id?: string
  subject_id: string
  grade_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingCreateOrConnectWithoutClassTimesInput = {
  where: Prisma.SubjectOfferingWhereUniqueInput
  create: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutClassTimesInput, Prisma.SubjectOfferingUncheckedCreateWithoutClassTimesInput>
}

export type SubjectOfferingUpsertWithoutClassTimesInput = {
  update: Prisma.XOR<Prisma.SubjectOfferingUpdateWithoutClassTimesInput, Prisma.SubjectOfferingUncheckedUpdateWithoutClassTimesInput>
  create: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutClassTimesInput, Prisma.SubjectOfferingUncheckedCreateWithoutClassTimesInput>
  where?: Prisma.SubjectOfferingWhereInput
}

export type SubjectOfferingUpdateToOneWithWhereWithoutClassTimesInput = {
  where?: Prisma.SubjectOfferingWhereInput
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateWithoutClassTimesInput, Prisma.SubjectOfferingUncheckedUpdateWithoutClassTimesInput>
}

export type SubjectOfferingUpdateWithoutClassTimesInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subject?: Prisma.SubjectUpdateOneRequiredWithoutOfferingsNestedInput
  grade?: Prisma.GradeUpdateOneRequiredWithoutOfferingsNestedInput
}

export type SubjectOfferingUncheckedUpdateWithoutClassTimesInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
  grade_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingCreateWithoutSubjectInput = {
  offering_id?: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
  grade: Prisma.GradeCreateNestedOneWithoutOfferingsInput
  classTimes?: Prisma.ClassTimeCreateNestedManyWithoutOfferingInput
}

export type SubjectOfferingUncheckedCreateWithoutSubjectInput = {
  offering_id?: string
  grade_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
  classTimes?: Prisma.ClassTimeUncheckedCreateNestedManyWithoutOfferingInput
}

export type SubjectOfferingCreateOrConnectWithoutSubjectInput = {
  where: Prisma.SubjectOfferingWhereUniqueInput
  create: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput>
}

export type SubjectOfferingCreateManySubjectInputEnvelope = {
  data: Prisma.SubjectOfferingCreateManySubjectInput | Prisma.SubjectOfferingCreateManySubjectInput[]
  skipDuplicates?: boolean
}

export type SubjectOfferingUpsertWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.SubjectOfferingWhereUniqueInput
  update: Prisma.XOR<Prisma.SubjectOfferingUpdateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedUpdateWithoutSubjectInput>
  create: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedCreateWithoutSubjectInput>
}

export type SubjectOfferingUpdateWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.SubjectOfferingWhereUniqueInput
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateWithoutSubjectInput, Prisma.SubjectOfferingUncheckedUpdateWithoutSubjectInput>
}

export type SubjectOfferingUpdateManyWithWhereWithoutSubjectInput = {
  where: Prisma.SubjectOfferingScalarWhereInput
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateManyMutationInput, Prisma.SubjectOfferingUncheckedUpdateManyWithoutSubjectInput>
}

export type SubjectOfferingScalarWhereInput = {
  AND?: Prisma.SubjectOfferingScalarWhereInput | Prisma.SubjectOfferingScalarWhereInput[]
  OR?: Prisma.SubjectOfferingScalarWhereInput[]
  NOT?: Prisma.SubjectOfferingScalarWhereInput | Prisma.SubjectOfferingScalarWhereInput[]
  offering_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  subject_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  grade_id?: Prisma.UuidFilter<"SubjectOffering"> | string
  location?: Prisma.EnumLocationFilter<"SubjectOffering"> | $Enums.Location
  price_per_term?: Prisma.DecimalFilter<"SubjectOffering"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingCreateWithoutGradeInput = {
  offering_id?: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
  subject: Prisma.SubjectCreateNestedOneWithoutOfferingsInput
  classTimes?: Prisma.ClassTimeCreateNestedManyWithoutOfferingInput
}

export type SubjectOfferingUncheckedCreateWithoutGradeInput = {
  offering_id?: string
  subject_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
  classTimes?: Prisma.ClassTimeUncheckedCreateNestedManyWithoutOfferingInput
}

export type SubjectOfferingCreateOrConnectWithoutGradeInput = {
  where: Prisma.SubjectOfferingWhereUniqueInput
  create: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutGradeInput, Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput>
}

export type SubjectOfferingCreateManyGradeInputEnvelope = {
  data: Prisma.SubjectOfferingCreateManyGradeInput | Prisma.SubjectOfferingCreateManyGradeInput[]
  skipDuplicates?: boolean
}

export type SubjectOfferingUpsertWithWhereUniqueWithoutGradeInput = {
  where: Prisma.SubjectOfferingWhereUniqueInput
  update: Prisma.XOR<Prisma.SubjectOfferingUpdateWithoutGradeInput, Prisma.SubjectOfferingUncheckedUpdateWithoutGradeInput>
  create: Prisma.XOR<Prisma.SubjectOfferingCreateWithoutGradeInput, Prisma.SubjectOfferingUncheckedCreateWithoutGradeInput>
}

export type SubjectOfferingUpdateWithWhereUniqueWithoutGradeInput = {
  where: Prisma.SubjectOfferingWhereUniqueInput
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateWithoutGradeInput, Prisma.SubjectOfferingUncheckedUpdateWithoutGradeInput>
}

export type SubjectOfferingUpdateManyWithWhereWithoutGradeInput = {
  where: Prisma.SubjectOfferingScalarWhereInput
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateManyMutationInput, Prisma.SubjectOfferingUncheckedUpdateManyWithoutGradeInput>
}

export type SubjectOfferingCreateManySubjectInput = {
  offering_id?: string
  grade_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingUpdateWithoutSubjectInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grade?: Prisma.GradeUpdateOneRequiredWithoutOfferingsNestedInput
  classTimes?: Prisma.ClassTimeUpdateManyWithoutOfferingNestedInput
}

export type SubjectOfferingUncheckedUpdateWithoutSubjectInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  grade_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  classTimes?: Prisma.ClassTimeUncheckedUpdateManyWithoutOfferingNestedInput
}

export type SubjectOfferingUncheckedUpdateManyWithoutSubjectInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  grade_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingCreateManyGradeInput = {
  offering_id?: string
  subject_id: string
  location: $Enums.Location
  price_per_term: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SubjectOfferingUpdateWithoutGradeInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subject?: Prisma.SubjectUpdateOneRequiredWithoutOfferingsNestedInput
  classTimes?: Prisma.ClassTimeUpdateManyWithoutOfferingNestedInput
}

export type SubjectOfferingUncheckedUpdateWithoutGradeInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  classTimes?: Prisma.ClassTimeUncheckedUpdateManyWithoutOfferingNestedInput
}

export type SubjectOfferingUncheckedUpdateManyWithoutGradeInput = {
  offering_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.EnumLocationFieldUpdateOperationsInput | $Enums.Location
  price_per_term?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}


/**
 * Count Type SubjectOfferingCountOutputType
 */

export type SubjectOfferingCountOutputType = {
  classTimes: number
}

export type SubjectOfferingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  classTimes?: boolean | SubjectOfferingCountOutputTypeCountClassTimesArgs
}

/**
 * SubjectOfferingCountOutputType without action
 */
export type SubjectOfferingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOfferingCountOutputType
   */
  select?: Prisma.SubjectOfferingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SubjectOfferingCountOutputType without action
 */
export type SubjectOfferingCountOutputTypeCountClassTimesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClassTimeWhereInput
}


export type SubjectOfferingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  offering_id?: boolean
  subject_id?: boolean
  grade_id?: boolean
  location?: boolean
  price_per_term?: boolean
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  grade?: boolean | Prisma.GradeDefaultArgs<ExtArgs>
  classTimes?: boolean | Prisma.SubjectOffering$classTimesArgs<ExtArgs>
  _count?: boolean | Prisma.SubjectOfferingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subjectOffering"]>

export type SubjectOfferingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  offering_id?: boolean
  subject_id?: boolean
  grade_id?: boolean
  location?: boolean
  price_per_term?: boolean
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  grade?: boolean | Prisma.GradeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subjectOffering"]>

export type SubjectOfferingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  offering_id?: boolean
  subject_id?: boolean
  grade_id?: boolean
  location?: boolean
  price_per_term?: boolean
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  grade?: boolean | Prisma.GradeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subjectOffering"]>

export type SubjectOfferingSelectScalar = {
  offering_id?: boolean
  subject_id?: boolean
  grade_id?: boolean
  location?: boolean
  price_per_term?: boolean
}

export type SubjectOfferingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"offering_id" | "subject_id" | "grade_id" | "location" | "price_per_term", ExtArgs["result"]["subjectOffering"]>
export type SubjectOfferingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  grade?: boolean | Prisma.GradeDefaultArgs<ExtArgs>
  classTimes?: boolean | Prisma.SubjectOffering$classTimesArgs<ExtArgs>
  _count?: boolean | Prisma.SubjectOfferingCountOutputTypeDefaultArgs<ExtArgs>
}
export type SubjectOfferingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  grade?: boolean | Prisma.GradeDefaultArgs<ExtArgs>
}
export type SubjectOfferingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  grade?: boolean | Prisma.GradeDefaultArgs<ExtArgs>
}

export type $SubjectOfferingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SubjectOffering"
  objects: {
    subject: Prisma.$SubjectPayload<ExtArgs>
    grade: Prisma.$GradePayload<ExtArgs>
    classTimes: Prisma.$ClassTimePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    offering_id: string
    subject_id: string
    grade_id: string
    location: $Enums.Location
    price_per_term: runtime.Decimal
  }, ExtArgs["result"]["subjectOffering"]>
  composites: {}
}

export type SubjectOfferingGetPayload<S extends boolean | null | undefined | SubjectOfferingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload, S>

export type SubjectOfferingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubjectOfferingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubjectOfferingCountAggregateInputType | true
  }

export interface SubjectOfferingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SubjectOffering'], meta: { name: 'SubjectOffering' } }
  /**
   * Find zero or one SubjectOffering that matches the filter.
   * @param {SubjectOfferingFindUniqueArgs} args - Arguments to find a SubjectOffering
   * @example
   * // Get one SubjectOffering
   * const subjectOffering = await prisma.subjectOffering.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubjectOfferingFindUniqueArgs>(args: Prisma.SelectSubset<T, SubjectOfferingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SubjectOffering that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubjectOfferingFindUniqueOrThrowArgs} args - Arguments to find a SubjectOffering
   * @example
   * // Get one SubjectOffering
   * const subjectOffering = await prisma.subjectOffering.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubjectOfferingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubjectOfferingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubjectOffering that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubjectOfferingFindFirstArgs} args - Arguments to find a SubjectOffering
   * @example
   * // Get one SubjectOffering
   * const subjectOffering = await prisma.subjectOffering.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubjectOfferingFindFirstArgs>(args?: Prisma.SelectSubset<T, SubjectOfferingFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubjectOffering that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubjectOfferingFindFirstOrThrowArgs} args - Arguments to find a SubjectOffering
   * @example
   * // Get one SubjectOffering
   * const subjectOffering = await prisma.subjectOffering.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubjectOfferingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubjectOfferingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SubjectOfferings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubjectOfferingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SubjectOfferings
   * const subjectOfferings = await prisma.subjectOffering.findMany()
   * 
   * // Get first 10 SubjectOfferings
   * const subjectOfferings = await prisma.subjectOffering.findMany({ take: 10 })
   * 
   * // Only select the `offering_id`
   * const subjectOfferingWithOffering_idOnly = await prisma.subjectOffering.findMany({ select: { offering_id: true } })
   * 
   */
  findMany<T extends SubjectOfferingFindManyArgs>(args?: Prisma.SelectSubset<T, SubjectOfferingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SubjectOffering.
   * @param {SubjectOfferingCreateArgs} args - Arguments to create a SubjectOffering.
   * @example
   * // Create one SubjectOffering
   * const SubjectOffering = await prisma.subjectOffering.create({
   *   data: {
   *     // ... data to create a SubjectOffering
   *   }
   * })
   * 
   */
  create<T extends SubjectOfferingCreateArgs>(args: Prisma.SelectSubset<T, SubjectOfferingCreateArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SubjectOfferings.
   * @param {SubjectOfferingCreateManyArgs} args - Arguments to create many SubjectOfferings.
   * @example
   * // Create many SubjectOfferings
   * const subjectOffering = await prisma.subjectOffering.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubjectOfferingCreateManyArgs>(args?: Prisma.SelectSubset<T, SubjectOfferingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SubjectOfferings and returns the data saved in the database.
   * @param {SubjectOfferingCreateManyAndReturnArgs} args - Arguments to create many SubjectOfferings.
   * @example
   * // Create many SubjectOfferings
   * const subjectOffering = await prisma.subjectOffering.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SubjectOfferings and only return the `offering_id`
   * const subjectOfferingWithOffering_idOnly = await prisma.subjectOffering.createManyAndReturn({
   *   select: { offering_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubjectOfferingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubjectOfferingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SubjectOffering.
   * @param {SubjectOfferingDeleteArgs} args - Arguments to delete one SubjectOffering.
   * @example
   * // Delete one SubjectOffering
   * const SubjectOffering = await prisma.subjectOffering.delete({
   *   where: {
   *     // ... filter to delete one SubjectOffering
   *   }
   * })
   * 
   */
  delete<T extends SubjectOfferingDeleteArgs>(args: Prisma.SelectSubset<T, SubjectOfferingDeleteArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SubjectOffering.
   * @param {SubjectOfferingUpdateArgs} args - Arguments to update one SubjectOffering.
   * @example
   * // Update one SubjectOffering
   * const subjectOffering = await prisma.subjectOffering.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubjectOfferingUpdateArgs>(args: Prisma.SelectSubset<T, SubjectOfferingUpdateArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SubjectOfferings.
   * @param {SubjectOfferingDeleteManyArgs} args - Arguments to filter SubjectOfferings to delete.
   * @example
   * // Delete a few SubjectOfferings
   * const { count } = await prisma.subjectOffering.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubjectOfferingDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubjectOfferingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubjectOfferings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubjectOfferingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SubjectOfferings
   * const subjectOffering = await prisma.subjectOffering.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubjectOfferingUpdateManyArgs>(args: Prisma.SelectSubset<T, SubjectOfferingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubjectOfferings and returns the data updated in the database.
   * @param {SubjectOfferingUpdateManyAndReturnArgs} args - Arguments to update many SubjectOfferings.
   * @example
   * // Update many SubjectOfferings
   * const subjectOffering = await prisma.subjectOffering.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SubjectOfferings and only return the `offering_id`
   * const subjectOfferingWithOffering_idOnly = await prisma.subjectOffering.updateManyAndReturn({
   *   select: { offering_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubjectOfferingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubjectOfferingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SubjectOffering.
   * @param {SubjectOfferingUpsertArgs} args - Arguments to update or create a SubjectOffering.
   * @example
   * // Update or create a SubjectOffering
   * const subjectOffering = await prisma.subjectOffering.upsert({
   *   create: {
   *     // ... data to create a SubjectOffering
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SubjectOffering we want to update
   *   }
   * })
   */
  upsert<T extends SubjectOfferingUpsertArgs>(args: Prisma.SelectSubset<T, SubjectOfferingUpsertArgs<ExtArgs>>): Prisma.Prisma__SubjectOfferingClient<runtime.Types.Result.GetResult<Prisma.$SubjectOfferingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SubjectOfferings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubjectOfferingCountArgs} args - Arguments to filter SubjectOfferings to count.
   * @example
   * // Count the number of SubjectOfferings
   * const count = await prisma.subjectOffering.count({
   *   where: {
   *     // ... the filter for the SubjectOfferings we want to count
   *   }
   * })
  **/
  count<T extends SubjectOfferingCountArgs>(
    args?: Prisma.Subset<T, SubjectOfferingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubjectOfferingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SubjectOffering.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubjectOfferingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubjectOfferingAggregateArgs>(args: Prisma.Subset<T, SubjectOfferingAggregateArgs>): Prisma.PrismaPromise<GetSubjectOfferingAggregateType<T>>

  /**
   * Group by SubjectOffering.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubjectOfferingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubjectOfferingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubjectOfferingGroupByArgs['orderBy'] }
      : { orderBy?: SubjectOfferingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubjectOfferingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubjectOfferingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SubjectOffering model
 */
readonly fields: SubjectOfferingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SubjectOffering.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubjectOfferingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subject<T extends Prisma.SubjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubjectDefaultArgs<ExtArgs>>): Prisma.Prisma__SubjectClient<runtime.Types.Result.GetResult<Prisma.$SubjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  grade<T extends Prisma.GradeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GradeDefaultArgs<ExtArgs>>): Prisma.Prisma__GradeClient<runtime.Types.Result.GetResult<Prisma.$GradePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  classTimes<T extends Prisma.SubjectOffering$classTimesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubjectOffering$classTimesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClassTimePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SubjectOffering model
 */
export interface SubjectOfferingFieldRefs {
  readonly offering_id: Prisma.FieldRef<"SubjectOffering", 'String'>
  readonly subject_id: Prisma.FieldRef<"SubjectOffering", 'String'>
  readonly grade_id: Prisma.FieldRef<"SubjectOffering", 'String'>
  readonly location: Prisma.FieldRef<"SubjectOffering", 'Location'>
  readonly price_per_term: Prisma.FieldRef<"SubjectOffering", 'Decimal'>
}
    

// Custom InputTypes
/**
 * SubjectOffering findUnique
 */
export type SubjectOfferingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * Filter, which SubjectOffering to fetch.
   */
  where: Prisma.SubjectOfferingWhereUniqueInput
}

/**
 * SubjectOffering findUniqueOrThrow
 */
export type SubjectOfferingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * Filter, which SubjectOffering to fetch.
   */
  where: Prisma.SubjectOfferingWhereUniqueInput
}

/**
 * SubjectOffering findFirst
 */
export type SubjectOfferingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * Filter, which SubjectOffering to fetch.
   */
  where?: Prisma.SubjectOfferingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubjectOfferings to fetch.
   */
  orderBy?: Prisma.SubjectOfferingOrderByWithRelationInput | Prisma.SubjectOfferingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubjectOfferings.
   */
  cursor?: Prisma.SubjectOfferingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubjectOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubjectOfferings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubjectOfferings.
   */
  distinct?: Prisma.SubjectOfferingScalarFieldEnum | Prisma.SubjectOfferingScalarFieldEnum[]
}

/**
 * SubjectOffering findFirstOrThrow
 */
export type SubjectOfferingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * Filter, which SubjectOffering to fetch.
   */
  where?: Prisma.SubjectOfferingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubjectOfferings to fetch.
   */
  orderBy?: Prisma.SubjectOfferingOrderByWithRelationInput | Prisma.SubjectOfferingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubjectOfferings.
   */
  cursor?: Prisma.SubjectOfferingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubjectOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubjectOfferings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubjectOfferings.
   */
  distinct?: Prisma.SubjectOfferingScalarFieldEnum | Prisma.SubjectOfferingScalarFieldEnum[]
}

/**
 * SubjectOffering findMany
 */
export type SubjectOfferingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * Filter, which SubjectOfferings to fetch.
   */
  where?: Prisma.SubjectOfferingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubjectOfferings to fetch.
   */
  orderBy?: Prisma.SubjectOfferingOrderByWithRelationInput | Prisma.SubjectOfferingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SubjectOfferings.
   */
  cursor?: Prisma.SubjectOfferingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubjectOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubjectOfferings.
   */
  skip?: number
  distinct?: Prisma.SubjectOfferingScalarFieldEnum | Prisma.SubjectOfferingScalarFieldEnum[]
}

/**
 * SubjectOffering create
 */
export type SubjectOfferingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * The data needed to create a SubjectOffering.
   */
  data: Prisma.XOR<Prisma.SubjectOfferingCreateInput, Prisma.SubjectOfferingUncheckedCreateInput>
}

/**
 * SubjectOffering createMany
 */
export type SubjectOfferingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SubjectOfferings.
   */
  data: Prisma.SubjectOfferingCreateManyInput | Prisma.SubjectOfferingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SubjectOffering createManyAndReturn
 */
export type SubjectOfferingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * The data used to create many SubjectOfferings.
   */
  data: Prisma.SubjectOfferingCreateManyInput | Prisma.SubjectOfferingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SubjectOffering update
 */
export type SubjectOfferingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * The data needed to update a SubjectOffering.
   */
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateInput, Prisma.SubjectOfferingUncheckedUpdateInput>
  /**
   * Choose, which SubjectOffering to update.
   */
  where: Prisma.SubjectOfferingWhereUniqueInput
}

/**
 * SubjectOffering updateMany
 */
export type SubjectOfferingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SubjectOfferings.
   */
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateManyMutationInput, Prisma.SubjectOfferingUncheckedUpdateManyInput>
  /**
   * Filter which SubjectOfferings to update
   */
  where?: Prisma.SubjectOfferingWhereInput
  /**
   * Limit how many SubjectOfferings to update.
   */
  limit?: number
}

/**
 * SubjectOffering updateManyAndReturn
 */
export type SubjectOfferingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * The data used to update SubjectOfferings.
   */
  data: Prisma.XOR<Prisma.SubjectOfferingUpdateManyMutationInput, Prisma.SubjectOfferingUncheckedUpdateManyInput>
  /**
   * Filter which SubjectOfferings to update
   */
  where?: Prisma.SubjectOfferingWhereInput
  /**
   * Limit how many SubjectOfferings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SubjectOffering upsert
 */
export type SubjectOfferingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * The filter to search for the SubjectOffering to update in case it exists.
   */
  where: Prisma.SubjectOfferingWhereUniqueInput
  /**
   * In case the SubjectOffering found by the `where` argument doesn't exist, create a new SubjectOffering with this data.
   */
  create: Prisma.XOR<Prisma.SubjectOfferingCreateInput, Prisma.SubjectOfferingUncheckedCreateInput>
  /**
   * In case the SubjectOffering was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubjectOfferingUpdateInput, Prisma.SubjectOfferingUncheckedUpdateInput>
}

/**
 * SubjectOffering delete
 */
export type SubjectOfferingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
  /**
   * Filter which SubjectOffering to delete.
   */
  where: Prisma.SubjectOfferingWhereUniqueInput
}

/**
 * SubjectOffering deleteMany
 */
export type SubjectOfferingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubjectOfferings to delete
   */
  where?: Prisma.SubjectOfferingWhereInput
  /**
   * Limit how many SubjectOfferings to delete.
   */
  limit?: number
}

/**
 * SubjectOffering.classTimes
 */
export type SubjectOffering$classTimesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClassTime
   */
  select?: Prisma.ClassTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClassTime
   */
  omit?: Prisma.ClassTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClassTimeInclude<ExtArgs> | null
  where?: Prisma.ClassTimeWhereInput
  orderBy?: Prisma.ClassTimeOrderByWithRelationInput | Prisma.ClassTimeOrderByWithRelationInput[]
  cursor?: Prisma.ClassTimeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ClassTimeScalarFieldEnum | Prisma.ClassTimeScalarFieldEnum[]
}

/**
 * SubjectOffering without action
 */
export type SubjectOfferingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubjectOffering
   */
  select?: Prisma.SubjectOfferingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubjectOffering
   */
  omit?: Prisma.SubjectOfferingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectOfferingInclude<ExtArgs> | null
}
