
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Term` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Term
 * 
 */
export type TermModel = runtime.Types.Result.DefaultSelection<Prisma.$TermPayload>

export type AggregateTerm = {
  _count: TermCountAggregateOutputType | null
  _avg: TermAvgAggregateOutputType | null
  _sum: TermSumAggregateOutputType | null
  _min: TermMinAggregateOutputType | null
  _max: TermMaxAggregateOutputType | null
}

export type TermAvgAggregateOutputType = {
  name: number | null
  year: number | null
}

export type TermSumAggregateOutputType = {
  name: number | null
  year: number | null
}

export type TermMinAggregateOutputType = {
  term_id: string | null
  name: number | null
  year: number | null
  start_date: Date | null
  end_date: Date | null
}

export type TermMaxAggregateOutputType = {
  term_id: string | null
  name: number | null
  year: number | null
  start_date: Date | null
  end_date: Date | null
}

export type TermCountAggregateOutputType = {
  term_id: number
  name: number
  year: number
  start_date: number
  end_date: number
  _all: number
}


export type TermAvgAggregateInputType = {
  name?: true
  year?: true
}

export type TermSumAggregateInputType = {
  name?: true
  year?: true
}

export type TermMinAggregateInputType = {
  term_id?: true
  name?: true
  year?: true
  start_date?: true
  end_date?: true
}

export type TermMaxAggregateInputType = {
  term_id?: true
  name?: true
  year?: true
  start_date?: true
  end_date?: true
}

export type TermCountAggregateInputType = {
  term_id?: true
  name?: true
  year?: true
  start_date?: true
  end_date?: true
  _all?: true
}

export type TermAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Term to aggregate.
   */
  where?: Prisma.TermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Terms to fetch.
   */
  orderBy?: Prisma.TermOrderByWithRelationInput | Prisma.TermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Terms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Terms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Terms
  **/
  _count?: true | TermCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TermAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TermSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TermMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TermMaxAggregateInputType
}

export type GetTermAggregateType<T extends TermAggregateArgs> = {
      [P in keyof T & keyof AggregateTerm]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTerm[P]>
    : Prisma.GetScalarType<T[P], AggregateTerm[P]>
}




export type TermGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TermWhereInput
  orderBy?: Prisma.TermOrderByWithAggregationInput | Prisma.TermOrderByWithAggregationInput[]
  by: Prisma.TermScalarFieldEnum[] | Prisma.TermScalarFieldEnum
  having?: Prisma.TermScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TermCountAggregateInputType | true
  _avg?: TermAvgAggregateInputType
  _sum?: TermSumAggregateInputType
  _min?: TermMinAggregateInputType
  _max?: TermMaxAggregateInputType
}

export type TermGroupByOutputType = {
  term_id: string
  name: number
  year: number
  start_date: Date
  end_date: Date
  _count: TermCountAggregateOutputType | null
  _avg: TermAvgAggregateOutputType | null
  _sum: TermSumAggregateOutputType | null
  _min: TermMinAggregateOutputType | null
  _max: TermMaxAggregateOutputType | null
}

type GetTermGroupByPayload<T extends TermGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TermGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TermGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TermGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TermGroupByOutputType[P]>
      }
    >
  >



export type TermWhereInput = {
  AND?: Prisma.TermWhereInput | Prisma.TermWhereInput[]
  OR?: Prisma.TermWhereInput[]
  NOT?: Prisma.TermWhereInput | Prisma.TermWhereInput[]
  term_id?: Prisma.UuidFilter<"Term"> | string
  name?: Prisma.IntFilter<"Term"> | number
  year?: Prisma.IntFilter<"Term"> | number
  start_date?: Prisma.DateTimeFilter<"Term"> | Date | string
  end_date?: Prisma.DateTimeFilter<"Term"> | Date | string
  enrolments?: Prisma.EnrolmentListRelationFilter
}

export type TermOrderByWithRelationInput = {
  term_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  year?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  enrolments?: Prisma.EnrolmentOrderByRelationAggregateInput
}

export type TermWhereUniqueInput = Prisma.AtLeast<{
  term_id?: string
  year_name?: Prisma.TermYearNameCompoundUniqueInput
  AND?: Prisma.TermWhereInput | Prisma.TermWhereInput[]
  OR?: Prisma.TermWhereInput[]
  NOT?: Prisma.TermWhereInput | Prisma.TermWhereInput[]
  name?: Prisma.IntFilter<"Term"> | number
  year?: Prisma.IntFilter<"Term"> | number
  start_date?: Prisma.DateTimeFilter<"Term"> | Date | string
  end_date?: Prisma.DateTimeFilter<"Term"> | Date | string
  enrolments?: Prisma.EnrolmentListRelationFilter
}, "term_id" | "year_name">

export type TermOrderByWithAggregationInput = {
  term_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  year?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  _count?: Prisma.TermCountOrderByAggregateInput
  _avg?: Prisma.TermAvgOrderByAggregateInput
  _max?: Prisma.TermMaxOrderByAggregateInput
  _min?: Prisma.TermMinOrderByAggregateInput
  _sum?: Prisma.TermSumOrderByAggregateInput
}

export type TermScalarWhereWithAggregatesInput = {
  AND?: Prisma.TermScalarWhereWithAggregatesInput | Prisma.TermScalarWhereWithAggregatesInput[]
  OR?: Prisma.TermScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TermScalarWhereWithAggregatesInput | Prisma.TermScalarWhereWithAggregatesInput[]
  term_id?: Prisma.UuidWithAggregatesFilter<"Term"> | string
  name?: Prisma.IntWithAggregatesFilter<"Term"> | number
  year?: Prisma.IntWithAggregatesFilter<"Term"> | number
  start_date?: Prisma.DateTimeWithAggregatesFilter<"Term"> | Date | string
  end_date?: Prisma.DateTimeWithAggregatesFilter<"Term"> | Date | string
}

export type TermCreateInput = {
  term_id?: string
  name: number
  year: number
  start_date: Date | string
  end_date: Date | string
  enrolments?: Prisma.EnrolmentCreateNestedManyWithoutTermInput
}

export type TermUncheckedCreateInput = {
  term_id?: string
  name: number
  year: number
  start_date: Date | string
  end_date: Date | string
  enrolments?: Prisma.EnrolmentUncheckedCreateNestedManyWithoutTermInput
}

export type TermUpdateInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  start_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrolments?: Prisma.EnrolmentUpdateManyWithoutTermNestedInput
}

export type TermUncheckedUpdateInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  start_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrolments?: Prisma.EnrolmentUncheckedUpdateManyWithoutTermNestedInput
}

export type TermCreateManyInput = {
  term_id?: string
  name: number
  year: number
  start_date: Date | string
  end_date: Date | string
}

export type TermUpdateManyMutationInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  start_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TermUncheckedUpdateManyInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  start_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TermYearNameCompoundUniqueInput = {
  year: number
  name: number
}

export type TermCountOrderByAggregateInput = {
  term_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  year?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
}

export type TermAvgOrderByAggregateInput = {
  name?: Prisma.SortOrder
  year?: Prisma.SortOrder
}

export type TermMaxOrderByAggregateInput = {
  term_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  year?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
}

export type TermMinOrderByAggregateInput = {
  term_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  year?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
}

export type TermSumOrderByAggregateInput = {
  name?: Prisma.SortOrder
  year?: Prisma.SortOrder
}

export type TermScalarRelationFilter = {
  is?: Prisma.TermWhereInput
  isNot?: Prisma.TermWhereInput
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type TermCreateNestedOneWithoutEnrolmentsInput = {
  create?: Prisma.XOR<Prisma.TermCreateWithoutEnrolmentsInput, Prisma.TermUncheckedCreateWithoutEnrolmentsInput>
  connectOrCreate?: Prisma.TermCreateOrConnectWithoutEnrolmentsInput
  connect?: Prisma.TermWhereUniqueInput
}

export type TermUpdateOneRequiredWithoutEnrolmentsNestedInput = {
  create?: Prisma.XOR<Prisma.TermCreateWithoutEnrolmentsInput, Prisma.TermUncheckedCreateWithoutEnrolmentsInput>
  connectOrCreate?: Prisma.TermCreateOrConnectWithoutEnrolmentsInput
  upsert?: Prisma.TermUpsertWithoutEnrolmentsInput
  connect?: Prisma.TermWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TermUpdateToOneWithWhereWithoutEnrolmentsInput, Prisma.TermUpdateWithoutEnrolmentsInput>, Prisma.TermUncheckedUpdateWithoutEnrolmentsInput>
}

export type TermCreateWithoutEnrolmentsInput = {
  term_id?: string
  name: number
  year: number
  start_date: Date | string
  end_date: Date | string
}

export type TermUncheckedCreateWithoutEnrolmentsInput = {
  term_id?: string
  name: number
  year: number
  start_date: Date | string
  end_date: Date | string
}

export type TermCreateOrConnectWithoutEnrolmentsInput = {
  where: Prisma.TermWhereUniqueInput
  create: Prisma.XOR<Prisma.TermCreateWithoutEnrolmentsInput, Prisma.TermUncheckedCreateWithoutEnrolmentsInput>
}

export type TermUpsertWithoutEnrolmentsInput = {
  update: Prisma.XOR<Prisma.TermUpdateWithoutEnrolmentsInput, Prisma.TermUncheckedUpdateWithoutEnrolmentsInput>
  create: Prisma.XOR<Prisma.TermCreateWithoutEnrolmentsInput, Prisma.TermUncheckedCreateWithoutEnrolmentsInput>
  where?: Prisma.TermWhereInput
}

export type TermUpdateToOneWithWhereWithoutEnrolmentsInput = {
  where?: Prisma.TermWhereInput
  data: Prisma.XOR<Prisma.TermUpdateWithoutEnrolmentsInput, Prisma.TermUncheckedUpdateWithoutEnrolmentsInput>
}

export type TermUpdateWithoutEnrolmentsInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  start_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TermUncheckedUpdateWithoutEnrolmentsInput = {
  term_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  start_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TermCountOutputType
 */

export type TermCountOutputType = {
  enrolments: number
}

export type TermCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  enrolments?: boolean | TermCountOutputTypeCountEnrolmentsArgs
}

/**
 * TermCountOutputType without action
 */
export type TermCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TermCountOutputType
   */
  select?: Prisma.TermCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TermCountOutputType without action
 */
export type TermCountOutputTypeCountEnrolmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EnrolmentWhereInput
}


export type TermSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  term_id?: boolean
  name?: boolean
  year?: boolean
  start_date?: boolean
  end_date?: boolean
  enrolments?: boolean | Prisma.Term$enrolmentsArgs<ExtArgs>
  _count?: boolean | Prisma.TermCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["term"]>

export type TermSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  term_id?: boolean
  name?: boolean
  year?: boolean
  start_date?: boolean
  end_date?: boolean
}, ExtArgs["result"]["term"]>

export type TermSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  term_id?: boolean
  name?: boolean
  year?: boolean
  start_date?: boolean
  end_date?: boolean
}, ExtArgs["result"]["term"]>

export type TermSelectScalar = {
  term_id?: boolean
  name?: boolean
  year?: boolean
  start_date?: boolean
  end_date?: boolean
}

export type TermOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"term_id" | "name" | "year" | "start_date" | "end_date", ExtArgs["result"]["term"]>
export type TermInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  enrolments?: boolean | Prisma.Term$enrolmentsArgs<ExtArgs>
  _count?: boolean | Prisma.TermCountOutputTypeDefaultArgs<ExtArgs>
}
export type TermIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TermIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TermPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Term"
  objects: {
    enrolments: Prisma.$EnrolmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    term_id: string
    name: number
    year: number
    start_date: Date
    end_date: Date
  }, ExtArgs["result"]["term"]>
  composites: {}
}

export type TermGetPayload<S extends boolean | null | undefined | TermDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TermPayload, S>

export type TermCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TermFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TermCountAggregateInputType | true
  }

export interface TermDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Term'], meta: { name: 'Term' } }
  /**
   * Find zero or one Term that matches the filter.
   * @param {TermFindUniqueArgs} args - Arguments to find a Term
   * @example
   * // Get one Term
   * const term = await prisma.term.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TermFindUniqueArgs>(args: Prisma.SelectSubset<T, TermFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Term that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TermFindUniqueOrThrowArgs} args - Arguments to find a Term
   * @example
   * // Get one Term
   * const term = await prisma.term.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TermFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TermFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Term that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TermFindFirstArgs} args - Arguments to find a Term
   * @example
   * // Get one Term
   * const term = await prisma.term.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TermFindFirstArgs>(args?: Prisma.SelectSubset<T, TermFindFirstArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Term that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TermFindFirstOrThrowArgs} args - Arguments to find a Term
   * @example
   * // Get one Term
   * const term = await prisma.term.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TermFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TermFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Terms that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TermFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Terms
   * const terms = await prisma.term.findMany()
   * 
   * // Get first 10 Terms
   * const terms = await prisma.term.findMany({ take: 10 })
   * 
   * // Only select the `term_id`
   * const termWithTerm_idOnly = await prisma.term.findMany({ select: { term_id: true } })
   * 
   */
  findMany<T extends TermFindManyArgs>(args?: Prisma.SelectSubset<T, TermFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Term.
   * @param {TermCreateArgs} args - Arguments to create a Term.
   * @example
   * // Create one Term
   * const Term = await prisma.term.create({
   *   data: {
   *     // ... data to create a Term
   *   }
   * })
   * 
   */
  create<T extends TermCreateArgs>(args: Prisma.SelectSubset<T, TermCreateArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Terms.
   * @param {TermCreateManyArgs} args - Arguments to create many Terms.
   * @example
   * // Create many Terms
   * const term = await prisma.term.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TermCreateManyArgs>(args?: Prisma.SelectSubset<T, TermCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Terms and returns the data saved in the database.
   * @param {TermCreateManyAndReturnArgs} args - Arguments to create many Terms.
   * @example
   * // Create many Terms
   * const term = await prisma.term.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Terms and only return the `term_id`
   * const termWithTerm_idOnly = await prisma.term.createManyAndReturn({
   *   select: { term_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TermCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TermCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Term.
   * @param {TermDeleteArgs} args - Arguments to delete one Term.
   * @example
   * // Delete one Term
   * const Term = await prisma.term.delete({
   *   where: {
   *     // ... filter to delete one Term
   *   }
   * })
   * 
   */
  delete<T extends TermDeleteArgs>(args: Prisma.SelectSubset<T, TermDeleteArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Term.
   * @param {TermUpdateArgs} args - Arguments to update one Term.
   * @example
   * // Update one Term
   * const term = await prisma.term.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TermUpdateArgs>(args: Prisma.SelectSubset<T, TermUpdateArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Terms.
   * @param {TermDeleteManyArgs} args - Arguments to filter Terms to delete.
   * @example
   * // Delete a few Terms
   * const { count } = await prisma.term.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TermDeleteManyArgs>(args?: Prisma.SelectSubset<T, TermDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Terms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TermUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Terms
   * const term = await prisma.term.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TermUpdateManyArgs>(args: Prisma.SelectSubset<T, TermUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Terms and returns the data updated in the database.
   * @param {TermUpdateManyAndReturnArgs} args - Arguments to update many Terms.
   * @example
   * // Update many Terms
   * const term = await prisma.term.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Terms and only return the `term_id`
   * const termWithTerm_idOnly = await prisma.term.updateManyAndReturn({
   *   select: { term_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TermUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TermUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Term.
   * @param {TermUpsertArgs} args - Arguments to update or create a Term.
   * @example
   * // Update or create a Term
   * const term = await prisma.term.upsert({
   *   create: {
   *     // ... data to create a Term
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Term we want to update
   *   }
   * })
   */
  upsert<T extends TermUpsertArgs>(args: Prisma.SelectSubset<T, TermUpsertArgs<ExtArgs>>): Prisma.Prisma__TermClient<runtime.Types.Result.GetResult<Prisma.$TermPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Terms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TermCountArgs} args - Arguments to filter Terms to count.
   * @example
   * // Count the number of Terms
   * const count = await prisma.term.count({
   *   where: {
   *     // ... the filter for the Terms we want to count
   *   }
   * })
  **/
  count<T extends TermCountArgs>(
    args?: Prisma.Subset<T, TermCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TermCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Term.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TermAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TermAggregateArgs>(args: Prisma.Subset<T, TermAggregateArgs>): Prisma.PrismaPromise<GetTermAggregateType<T>>

  /**
   * Group by Term.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TermGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TermGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TermGroupByArgs['orderBy'] }
      : { orderBy?: TermGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TermGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTermGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Term model
 */
readonly fields: TermFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Term.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TermClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  enrolments<T extends Prisma.Term$enrolmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Term$enrolmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EnrolmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Term model
 */
export interface TermFieldRefs {
  readonly term_id: Prisma.FieldRef<"Term", 'String'>
  readonly name: Prisma.FieldRef<"Term", 'Int'>
  readonly year: Prisma.FieldRef<"Term", 'Int'>
  readonly start_date: Prisma.FieldRef<"Term", 'DateTime'>
  readonly end_date: Prisma.FieldRef<"Term", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Term findUnique
 */
export type TermFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * Filter, which Term to fetch.
   */
  where: Prisma.TermWhereUniqueInput
}

/**
 * Term findUniqueOrThrow
 */
export type TermFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * Filter, which Term to fetch.
   */
  where: Prisma.TermWhereUniqueInput
}

/**
 * Term findFirst
 */
export type TermFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * Filter, which Term to fetch.
   */
  where?: Prisma.TermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Terms to fetch.
   */
  orderBy?: Prisma.TermOrderByWithRelationInput | Prisma.TermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Terms.
   */
  cursor?: Prisma.TermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Terms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Terms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Terms.
   */
  distinct?: Prisma.TermScalarFieldEnum | Prisma.TermScalarFieldEnum[]
}

/**
 * Term findFirstOrThrow
 */
export type TermFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * Filter, which Term to fetch.
   */
  where?: Prisma.TermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Terms to fetch.
   */
  orderBy?: Prisma.TermOrderByWithRelationInput | Prisma.TermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Terms.
   */
  cursor?: Prisma.TermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Terms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Terms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Terms.
   */
  distinct?: Prisma.TermScalarFieldEnum | Prisma.TermScalarFieldEnum[]
}

/**
 * Term findMany
 */
export type TermFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * Filter, which Terms to fetch.
   */
  where?: Prisma.TermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Terms to fetch.
   */
  orderBy?: Prisma.TermOrderByWithRelationInput | Prisma.TermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Terms.
   */
  cursor?: Prisma.TermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Terms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Terms.
   */
  skip?: number
  distinct?: Prisma.TermScalarFieldEnum | Prisma.TermScalarFieldEnum[]
}

/**
 * Term create
 */
export type TermCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * The data needed to create a Term.
   */
  data: Prisma.XOR<Prisma.TermCreateInput, Prisma.TermUncheckedCreateInput>
}

/**
 * Term createMany
 */
export type TermCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Terms.
   */
  data: Prisma.TermCreateManyInput | Prisma.TermCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Term createManyAndReturn
 */
export type TermCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * The data used to create many Terms.
   */
  data: Prisma.TermCreateManyInput | Prisma.TermCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Term update
 */
export type TermUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * The data needed to update a Term.
   */
  data: Prisma.XOR<Prisma.TermUpdateInput, Prisma.TermUncheckedUpdateInput>
  /**
   * Choose, which Term to update.
   */
  where: Prisma.TermWhereUniqueInput
}

/**
 * Term updateMany
 */
export type TermUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Terms.
   */
  data: Prisma.XOR<Prisma.TermUpdateManyMutationInput, Prisma.TermUncheckedUpdateManyInput>
  /**
   * Filter which Terms to update
   */
  where?: Prisma.TermWhereInput
  /**
   * Limit how many Terms to update.
   */
  limit?: number
}

/**
 * Term updateManyAndReturn
 */
export type TermUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * The data used to update Terms.
   */
  data: Prisma.XOR<Prisma.TermUpdateManyMutationInput, Prisma.TermUncheckedUpdateManyInput>
  /**
   * Filter which Terms to update
   */
  where?: Prisma.TermWhereInput
  /**
   * Limit how many Terms to update.
   */
  limit?: number
}

/**
 * Term upsert
 */
export type TermUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * The filter to search for the Term to update in case it exists.
   */
  where: Prisma.TermWhereUniqueInput
  /**
   * In case the Term found by the `where` argument doesn't exist, create a new Term with this data.
   */
  create: Prisma.XOR<Prisma.TermCreateInput, Prisma.TermUncheckedCreateInput>
  /**
   * In case the Term was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TermUpdateInput, Prisma.TermUncheckedUpdateInput>
}

/**
 * Term delete
 */
export type TermDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
  /**
   * Filter which Term to delete.
   */
  where: Prisma.TermWhereUniqueInput
}

/**
 * Term deleteMany
 */
export type TermDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Terms to delete
   */
  where?: Prisma.TermWhereInput
  /**
   * Limit how many Terms to delete.
   */
  limit?: number
}

/**
 * Term.enrolments
 */
export type Term$enrolmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Enrolment
   */
  select?: Prisma.EnrolmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Enrolment
   */
  omit?: Prisma.EnrolmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EnrolmentInclude<ExtArgs> | null
  where?: Prisma.EnrolmentWhereInput
  orderBy?: Prisma.EnrolmentOrderByWithRelationInput | Prisma.EnrolmentOrderByWithRelationInput[]
  cursor?: Prisma.EnrolmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EnrolmentScalarFieldEnum | Prisma.EnrolmentScalarFieldEnum[]
}

/**
 * Term without action
 */
export type TermDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Term
   */
  select?: Prisma.TermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Term
   */
  omit?: Prisma.TermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TermInclude<ExtArgs> | null
}
