
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TutorDetails` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TutorDetails
 * 
 */
export type TutorDetailsModel = runtime.Types.Result.DefaultSelection<Prisma.$TutorDetailsPayload>

export type AggregateTutorDetails = {
  _count: TutorDetailsCountAggregateOutputType | null
  _avg: TutorDetailsAvgAggregateOutputType | null
  _sum: TutorDetailsSumAggregateOutputType | null
  _min: TutorDetailsMinAggregateOutputType | null
  _max: TutorDetailsMaxAggregateOutputType | null
}

export type TutorDetailsAvgAggregateOutputType = {
  start_hourly_rate: runtime.Decimal | null
}

export type TutorDetailsSumAggregateOutputType = {
  start_hourly_rate: runtime.Decimal | null
}

export type TutorDetailsMinAggregateOutputType = {
  tutor_id: string | null
  date_of_birth: Date | null
  gender: string | null
  address: string | null
  job: string | null
  start_date: Date | null
  end_date: Date | null
  emergency_contact_name: string | null
  emergency_contact_mobile: string | null
  start_hourly_rate: runtime.Decimal | null
  tfn: string | null
  account_name: string | null
  bsb: string | null
  account_number: string | null
  super_name: string | null
  super_member_number: string | null
  high_school: string | null
  university_course: string | null
  working_with_children: string | null
  police_check: string | null
  special_skills: string | null
}

export type TutorDetailsMaxAggregateOutputType = {
  tutor_id: string | null
  date_of_birth: Date | null
  gender: string | null
  address: string | null
  job: string | null
  start_date: Date | null
  end_date: Date | null
  emergency_contact_name: string | null
  emergency_contact_mobile: string | null
  start_hourly_rate: runtime.Decimal | null
  tfn: string | null
  account_name: string | null
  bsb: string | null
  account_number: string | null
  super_name: string | null
  super_member_number: string | null
  high_school: string | null
  university_course: string | null
  working_with_children: string | null
  police_check: string | null
  special_skills: string | null
}

export type TutorDetailsCountAggregateOutputType = {
  tutor_id: number
  date_of_birth: number
  gender: number
  address: number
  job: number
  start_date: number
  end_date: number
  emergency_contact_name: number
  emergency_contact_mobile: number
  start_hourly_rate: number
  tfn: number
  account_name: number
  bsb: number
  account_number: number
  super_name: number
  super_member_number: number
  high_school: number
  university_course: number
  working_with_children: number
  police_check: number
  special_skills: number
  hsc_subjects: number
  _all: number
}


export type TutorDetailsAvgAggregateInputType = {
  start_hourly_rate?: true
}

export type TutorDetailsSumAggregateInputType = {
  start_hourly_rate?: true
}

export type TutorDetailsMinAggregateInputType = {
  tutor_id?: true
  date_of_birth?: true
  gender?: true
  address?: true
  job?: true
  start_date?: true
  end_date?: true
  emergency_contact_name?: true
  emergency_contact_mobile?: true
  start_hourly_rate?: true
  tfn?: true
  account_name?: true
  bsb?: true
  account_number?: true
  super_name?: true
  super_member_number?: true
  high_school?: true
  university_course?: true
  working_with_children?: true
  police_check?: true
  special_skills?: true
}

export type TutorDetailsMaxAggregateInputType = {
  tutor_id?: true
  date_of_birth?: true
  gender?: true
  address?: true
  job?: true
  start_date?: true
  end_date?: true
  emergency_contact_name?: true
  emergency_contact_mobile?: true
  start_hourly_rate?: true
  tfn?: true
  account_name?: true
  bsb?: true
  account_number?: true
  super_name?: true
  super_member_number?: true
  high_school?: true
  university_course?: true
  working_with_children?: true
  police_check?: true
  special_skills?: true
}

export type TutorDetailsCountAggregateInputType = {
  tutor_id?: true
  date_of_birth?: true
  gender?: true
  address?: true
  job?: true
  start_date?: true
  end_date?: true
  emergency_contact_name?: true
  emergency_contact_mobile?: true
  start_hourly_rate?: true
  tfn?: true
  account_name?: true
  bsb?: true
  account_number?: true
  super_name?: true
  super_member_number?: true
  high_school?: true
  university_course?: true
  working_with_children?: true
  police_check?: true
  special_skills?: true
  hsc_subjects?: true
  _all?: true
}

export type TutorDetailsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TutorDetails to aggregate.
   */
  where?: Prisma.TutorDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorDetails to fetch.
   */
  orderBy?: Prisma.TutorDetailsOrderByWithRelationInput | Prisma.TutorDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TutorDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TutorDetails
  **/
  _count?: true | TutorDetailsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TutorDetailsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TutorDetailsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TutorDetailsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TutorDetailsMaxAggregateInputType
}

export type GetTutorDetailsAggregateType<T extends TutorDetailsAggregateArgs> = {
      [P in keyof T & keyof AggregateTutorDetails]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTutorDetails[P]>
    : Prisma.GetScalarType<T[P], AggregateTutorDetails[P]>
}




export type TutorDetailsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TutorDetailsWhereInput
  orderBy?: Prisma.TutorDetailsOrderByWithAggregationInput | Prisma.TutorDetailsOrderByWithAggregationInput[]
  by: Prisma.TutorDetailsScalarFieldEnum[] | Prisma.TutorDetailsScalarFieldEnum
  having?: Prisma.TutorDetailsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TutorDetailsCountAggregateInputType | true
  _avg?: TutorDetailsAvgAggregateInputType
  _sum?: TutorDetailsSumAggregateInputType
  _min?: TutorDetailsMinAggregateInputType
  _max?: TutorDetailsMaxAggregateInputType
}

export type TutorDetailsGroupByOutputType = {
  tutor_id: string
  date_of_birth: Date | null
  gender: string | null
  address: string | null
  job: string
  start_date: Date | null
  end_date: Date | null
  emergency_contact_name: string | null
  emergency_contact_mobile: string | null
  start_hourly_rate: runtime.Decimal | null
  tfn: string | null
  account_name: string | null
  bsb: string | null
  account_number: string | null
  super_name: string | null
  super_member_number: string | null
  high_school: string | null
  university_course: string | null
  working_with_children: string | null
  police_check: string | null
  special_skills: string | null
  hsc_subjects: string[]
  _count: TutorDetailsCountAggregateOutputType | null
  _avg: TutorDetailsAvgAggregateOutputType | null
  _sum: TutorDetailsSumAggregateOutputType | null
  _min: TutorDetailsMinAggregateOutputType | null
  _max: TutorDetailsMaxAggregateOutputType | null
}

type GetTutorDetailsGroupByPayload<T extends TutorDetailsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TutorDetailsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TutorDetailsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TutorDetailsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TutorDetailsGroupByOutputType[P]>
      }
    >
  >



export type TutorDetailsWhereInput = {
  AND?: Prisma.TutorDetailsWhereInput | Prisma.TutorDetailsWhereInput[]
  OR?: Prisma.TutorDetailsWhereInput[]
  NOT?: Prisma.TutorDetailsWhereInput | Prisma.TutorDetailsWhereInput[]
  tutor_id?: Prisma.UuidFilter<"TutorDetails"> | string
  date_of_birth?: Prisma.DateTimeNullableFilter<"TutorDetails"> | Date | string | null
  gender?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  address?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  job?: Prisma.StringFilter<"TutorDetails"> | string
  start_date?: Prisma.DateTimeNullableFilter<"TutorDetails"> | Date | string | null
  end_date?: Prisma.DateTimeNullableFilter<"TutorDetails"> | Date | string | null
  emergency_contact_name?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  emergency_contact_mobile?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  start_hourly_rate?: Prisma.DecimalNullableFilter<"TutorDetails"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  account_name?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  bsb?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  account_number?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  super_name?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  super_member_number?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  high_school?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  university_course?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  working_with_children?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  police_check?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  special_skills?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  hsc_subjects?: Prisma.StringNullableListFilter<"TutorDetails">
  tutor?: Prisma.XOR<Prisma.TutorScalarRelationFilter, Prisma.TutorWhereInput>
}

export type TutorDetailsOrderByWithRelationInput = {
  tutor_id?: Prisma.SortOrder
  date_of_birth?: Prisma.SortOrderInput | Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  job?: Prisma.SortOrder
  start_date?: Prisma.SortOrderInput | Prisma.SortOrder
  end_date?: Prisma.SortOrderInput | Prisma.SortOrder
  emergency_contact_name?: Prisma.SortOrderInput | Prisma.SortOrder
  emergency_contact_mobile?: Prisma.SortOrderInput | Prisma.SortOrder
  start_hourly_rate?: Prisma.SortOrderInput | Prisma.SortOrder
  tfn?: Prisma.SortOrderInput | Prisma.SortOrder
  account_name?: Prisma.SortOrderInput | Prisma.SortOrder
  bsb?: Prisma.SortOrderInput | Prisma.SortOrder
  account_number?: Prisma.SortOrderInput | Prisma.SortOrder
  super_name?: Prisma.SortOrderInput | Prisma.SortOrder
  super_member_number?: Prisma.SortOrderInput | Prisma.SortOrder
  high_school?: Prisma.SortOrderInput | Prisma.SortOrder
  university_course?: Prisma.SortOrderInput | Prisma.SortOrder
  working_with_children?: Prisma.SortOrderInput | Prisma.SortOrder
  police_check?: Prisma.SortOrderInput | Prisma.SortOrder
  special_skills?: Prisma.SortOrderInput | Prisma.SortOrder
  hsc_subjects?: Prisma.SortOrder
  tutor?: Prisma.TutorOrderByWithRelationInput
}

export type TutorDetailsWhereUniqueInput = Prisma.AtLeast<{
  tutor_id?: string
  AND?: Prisma.TutorDetailsWhereInput | Prisma.TutorDetailsWhereInput[]
  OR?: Prisma.TutorDetailsWhereInput[]
  NOT?: Prisma.TutorDetailsWhereInput | Prisma.TutorDetailsWhereInput[]
  date_of_birth?: Prisma.DateTimeNullableFilter<"TutorDetails"> | Date | string | null
  gender?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  address?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  job?: Prisma.StringFilter<"TutorDetails"> | string
  start_date?: Prisma.DateTimeNullableFilter<"TutorDetails"> | Date | string | null
  end_date?: Prisma.DateTimeNullableFilter<"TutorDetails"> | Date | string | null
  emergency_contact_name?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  emergency_contact_mobile?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  start_hourly_rate?: Prisma.DecimalNullableFilter<"TutorDetails"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  account_name?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  bsb?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  account_number?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  super_name?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  super_member_number?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  high_school?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  university_course?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  working_with_children?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  police_check?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  special_skills?: Prisma.StringNullableFilter<"TutorDetails"> | string | null
  hsc_subjects?: Prisma.StringNullableListFilter<"TutorDetails">
  tutor?: Prisma.XOR<Prisma.TutorScalarRelationFilter, Prisma.TutorWhereInput>
}, "tutor_id">

export type TutorDetailsOrderByWithAggregationInput = {
  tutor_id?: Prisma.SortOrder
  date_of_birth?: Prisma.SortOrderInput | Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  job?: Prisma.SortOrder
  start_date?: Prisma.SortOrderInput | Prisma.SortOrder
  end_date?: Prisma.SortOrderInput | Prisma.SortOrder
  emergency_contact_name?: Prisma.SortOrderInput | Prisma.SortOrder
  emergency_contact_mobile?: Prisma.SortOrderInput | Prisma.SortOrder
  start_hourly_rate?: Prisma.SortOrderInput | Prisma.SortOrder
  tfn?: Prisma.SortOrderInput | Prisma.SortOrder
  account_name?: Prisma.SortOrderInput | Prisma.SortOrder
  bsb?: Prisma.SortOrderInput | Prisma.SortOrder
  account_number?: Prisma.SortOrderInput | Prisma.SortOrder
  super_name?: Prisma.SortOrderInput | Prisma.SortOrder
  super_member_number?: Prisma.SortOrderInput | Prisma.SortOrder
  high_school?: Prisma.SortOrderInput | Prisma.SortOrder
  university_course?: Prisma.SortOrderInput | Prisma.SortOrder
  working_with_children?: Prisma.SortOrderInput | Prisma.SortOrder
  police_check?: Prisma.SortOrderInput | Prisma.SortOrder
  special_skills?: Prisma.SortOrderInput | Prisma.SortOrder
  hsc_subjects?: Prisma.SortOrder
  _count?: Prisma.TutorDetailsCountOrderByAggregateInput
  _avg?: Prisma.TutorDetailsAvgOrderByAggregateInput
  _max?: Prisma.TutorDetailsMaxOrderByAggregateInput
  _min?: Prisma.TutorDetailsMinOrderByAggregateInput
  _sum?: Prisma.TutorDetailsSumOrderByAggregateInput
}

export type TutorDetailsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TutorDetailsScalarWhereWithAggregatesInput | Prisma.TutorDetailsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TutorDetailsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TutorDetailsScalarWhereWithAggregatesInput | Prisma.TutorDetailsScalarWhereWithAggregatesInput[]
  tutor_id?: Prisma.UuidWithAggregatesFilter<"TutorDetails"> | string
  date_of_birth?: Prisma.DateTimeNullableWithAggregatesFilter<"TutorDetails"> | Date | string | null
  gender?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  job?: Prisma.StringWithAggregatesFilter<"TutorDetails"> | string
  start_date?: Prisma.DateTimeNullableWithAggregatesFilter<"TutorDetails"> | Date | string | null
  end_date?: Prisma.DateTimeNullableWithAggregatesFilter<"TutorDetails"> | Date | string | null
  emergency_contact_name?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  emergency_contact_mobile?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  start_hourly_rate?: Prisma.DecimalNullableWithAggregatesFilter<"TutorDetails"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  account_name?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  bsb?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  account_number?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  super_name?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  super_member_number?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  high_school?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  university_course?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  working_with_children?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  police_check?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  special_skills?: Prisma.StringNullableWithAggregatesFilter<"TutorDetails"> | string | null
  hsc_subjects?: Prisma.StringNullableListFilter<"TutorDetails">
}

export type TutorDetailsCreateInput = {
  date_of_birth?: Date | string | null
  gender?: string | null
  address?: string | null
  job?: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  emergency_contact_name?: string | null
  emergency_contact_mobile?: string | null
  start_hourly_rate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: string | null
  account_name?: string | null
  bsb?: string | null
  account_number?: string | null
  super_name?: string | null
  super_member_number?: string | null
  high_school?: string | null
  university_course?: string | null
  working_with_children?: string | null
  police_check?: string | null
  special_skills?: string | null
  hsc_subjects?: Prisma.TutorDetailsCreatehsc_subjectsInput | string[]
  tutor: Prisma.TutorCreateNestedOneWithoutDetailsInput
}

export type TutorDetailsUncheckedCreateInput = {
  tutor_id: string
  date_of_birth?: Date | string | null
  gender?: string | null
  address?: string | null
  job?: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  emergency_contact_name?: string | null
  emergency_contact_mobile?: string | null
  start_hourly_rate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: string | null
  account_name?: string | null
  bsb?: string | null
  account_number?: string | null
  super_name?: string | null
  super_member_number?: string | null
  high_school?: string | null
  university_course?: string | null
  working_with_children?: string | null
  police_check?: string | null
  special_skills?: string | null
  hsc_subjects?: Prisma.TutorDetailsCreatehsc_subjectsInput | string[]
}

export type TutorDetailsUpdateInput = {
  date_of_birth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  emergency_contact_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergency_contact_mobile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_hourly_rate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bsb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_member_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  high_school?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  university_course?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  working_with_children?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  police_check?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  special_skills?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hsc_subjects?: Prisma.TutorDetailsUpdatehsc_subjectsInput | string[]
  tutor?: Prisma.TutorUpdateOneRequiredWithoutDetailsNestedInput
}

export type TutorDetailsUncheckedUpdateInput = {
  tutor_id?: Prisma.StringFieldUpdateOperationsInput | string
  date_of_birth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  emergency_contact_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergency_contact_mobile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_hourly_rate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bsb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_member_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  high_school?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  university_course?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  working_with_children?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  police_check?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  special_skills?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hsc_subjects?: Prisma.TutorDetailsUpdatehsc_subjectsInput | string[]
}

export type TutorDetailsCreateManyInput = {
  tutor_id: string
  date_of_birth?: Date | string | null
  gender?: string | null
  address?: string | null
  job?: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  emergency_contact_name?: string | null
  emergency_contact_mobile?: string | null
  start_hourly_rate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: string | null
  account_name?: string | null
  bsb?: string | null
  account_number?: string | null
  super_name?: string | null
  super_member_number?: string | null
  high_school?: string | null
  university_course?: string | null
  working_with_children?: string | null
  police_check?: string | null
  special_skills?: string | null
  hsc_subjects?: Prisma.TutorDetailsCreatehsc_subjectsInput | string[]
}

export type TutorDetailsUpdateManyMutationInput = {
  date_of_birth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  emergency_contact_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergency_contact_mobile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_hourly_rate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bsb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_member_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  high_school?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  university_course?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  working_with_children?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  police_check?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  special_skills?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hsc_subjects?: Prisma.TutorDetailsUpdatehsc_subjectsInput | string[]
}

export type TutorDetailsUncheckedUpdateManyInput = {
  tutor_id?: Prisma.StringFieldUpdateOperationsInput | string
  date_of_birth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  emergency_contact_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergency_contact_mobile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_hourly_rate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bsb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_member_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  high_school?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  university_course?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  working_with_children?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  police_check?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  special_skills?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hsc_subjects?: Prisma.TutorDetailsUpdatehsc_subjectsInput | string[]
}

export type TutorDetailsNullableScalarRelationFilter = {
  is?: Prisma.TutorDetailsWhereInput | null
  isNot?: Prisma.TutorDetailsWhereInput | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type TutorDetailsCountOrderByAggregateInput = {
  tutor_id?: Prisma.SortOrder
  date_of_birth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  job?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  emergency_contact_name?: Prisma.SortOrder
  emergency_contact_mobile?: Prisma.SortOrder
  start_hourly_rate?: Prisma.SortOrder
  tfn?: Prisma.SortOrder
  account_name?: Prisma.SortOrder
  bsb?: Prisma.SortOrder
  account_number?: Prisma.SortOrder
  super_name?: Prisma.SortOrder
  super_member_number?: Prisma.SortOrder
  high_school?: Prisma.SortOrder
  university_course?: Prisma.SortOrder
  working_with_children?: Prisma.SortOrder
  police_check?: Prisma.SortOrder
  special_skills?: Prisma.SortOrder
  hsc_subjects?: Prisma.SortOrder
}

export type TutorDetailsAvgOrderByAggregateInput = {
  start_hourly_rate?: Prisma.SortOrder
}

export type TutorDetailsMaxOrderByAggregateInput = {
  tutor_id?: Prisma.SortOrder
  date_of_birth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  job?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  emergency_contact_name?: Prisma.SortOrder
  emergency_contact_mobile?: Prisma.SortOrder
  start_hourly_rate?: Prisma.SortOrder
  tfn?: Prisma.SortOrder
  account_name?: Prisma.SortOrder
  bsb?: Prisma.SortOrder
  account_number?: Prisma.SortOrder
  super_name?: Prisma.SortOrder
  super_member_number?: Prisma.SortOrder
  high_school?: Prisma.SortOrder
  university_course?: Prisma.SortOrder
  working_with_children?: Prisma.SortOrder
  police_check?: Prisma.SortOrder
  special_skills?: Prisma.SortOrder
}

export type TutorDetailsMinOrderByAggregateInput = {
  tutor_id?: Prisma.SortOrder
  date_of_birth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  job?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  emergency_contact_name?: Prisma.SortOrder
  emergency_contact_mobile?: Prisma.SortOrder
  start_hourly_rate?: Prisma.SortOrder
  tfn?: Prisma.SortOrder
  account_name?: Prisma.SortOrder
  bsb?: Prisma.SortOrder
  account_number?: Prisma.SortOrder
  super_name?: Prisma.SortOrder
  super_member_number?: Prisma.SortOrder
  high_school?: Prisma.SortOrder
  university_course?: Prisma.SortOrder
  working_with_children?: Prisma.SortOrder
  police_check?: Prisma.SortOrder
  special_skills?: Prisma.SortOrder
}

export type TutorDetailsSumOrderByAggregateInput = {
  start_hourly_rate?: Prisma.SortOrder
}

export type TutorDetailsCreateNestedOneWithoutTutorInput = {
  create?: Prisma.XOR<Prisma.TutorDetailsCreateWithoutTutorInput, Prisma.TutorDetailsUncheckedCreateWithoutTutorInput>
  connectOrCreate?: Prisma.TutorDetailsCreateOrConnectWithoutTutorInput
  connect?: Prisma.TutorDetailsWhereUniqueInput
}

export type TutorDetailsUncheckedCreateNestedOneWithoutTutorInput = {
  create?: Prisma.XOR<Prisma.TutorDetailsCreateWithoutTutorInput, Prisma.TutorDetailsUncheckedCreateWithoutTutorInput>
  connectOrCreate?: Prisma.TutorDetailsCreateOrConnectWithoutTutorInput
  connect?: Prisma.TutorDetailsWhereUniqueInput
}

export type TutorDetailsUpdateOneWithoutTutorNestedInput = {
  create?: Prisma.XOR<Prisma.TutorDetailsCreateWithoutTutorInput, Prisma.TutorDetailsUncheckedCreateWithoutTutorInput>
  connectOrCreate?: Prisma.TutorDetailsCreateOrConnectWithoutTutorInput
  upsert?: Prisma.TutorDetailsUpsertWithoutTutorInput
  disconnect?: Prisma.TutorDetailsWhereInput | boolean
  delete?: Prisma.TutorDetailsWhereInput | boolean
  connect?: Prisma.TutorDetailsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TutorDetailsUpdateToOneWithWhereWithoutTutorInput, Prisma.TutorDetailsUpdateWithoutTutorInput>, Prisma.TutorDetailsUncheckedUpdateWithoutTutorInput>
}

export type TutorDetailsUncheckedUpdateOneWithoutTutorNestedInput = {
  create?: Prisma.XOR<Prisma.TutorDetailsCreateWithoutTutorInput, Prisma.TutorDetailsUncheckedCreateWithoutTutorInput>
  connectOrCreate?: Prisma.TutorDetailsCreateOrConnectWithoutTutorInput
  upsert?: Prisma.TutorDetailsUpsertWithoutTutorInput
  disconnect?: Prisma.TutorDetailsWhereInput | boolean
  delete?: Prisma.TutorDetailsWhereInput | boolean
  connect?: Prisma.TutorDetailsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TutorDetailsUpdateToOneWithWhereWithoutTutorInput, Prisma.TutorDetailsUpdateWithoutTutorInput>, Prisma.TutorDetailsUncheckedUpdateWithoutTutorInput>
}

export type TutorDetailsCreatehsc_subjectsInput = {
  set: string[]
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type TutorDetailsUpdatehsc_subjectsInput = {
  set?: string[]
  push?: string | string[]
}

export type TutorDetailsCreateWithoutTutorInput = {
  date_of_birth?: Date | string | null
  gender?: string | null
  address?: string | null
  job?: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  emergency_contact_name?: string | null
  emergency_contact_mobile?: string | null
  start_hourly_rate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: string | null
  account_name?: string | null
  bsb?: string | null
  account_number?: string | null
  super_name?: string | null
  super_member_number?: string | null
  high_school?: string | null
  university_course?: string | null
  working_with_children?: string | null
  police_check?: string | null
  special_skills?: string | null
  hsc_subjects?: Prisma.TutorDetailsCreatehsc_subjectsInput | string[]
}

export type TutorDetailsUncheckedCreateWithoutTutorInput = {
  date_of_birth?: Date | string | null
  gender?: string | null
  address?: string | null
  job?: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  emergency_contact_name?: string | null
  emergency_contact_mobile?: string | null
  start_hourly_rate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: string | null
  account_name?: string | null
  bsb?: string | null
  account_number?: string | null
  super_name?: string | null
  super_member_number?: string | null
  high_school?: string | null
  university_course?: string | null
  working_with_children?: string | null
  police_check?: string | null
  special_skills?: string | null
  hsc_subjects?: Prisma.TutorDetailsCreatehsc_subjectsInput | string[]
}

export type TutorDetailsCreateOrConnectWithoutTutorInput = {
  where: Prisma.TutorDetailsWhereUniqueInput
  create: Prisma.XOR<Prisma.TutorDetailsCreateWithoutTutorInput, Prisma.TutorDetailsUncheckedCreateWithoutTutorInput>
}

export type TutorDetailsUpsertWithoutTutorInput = {
  update: Prisma.XOR<Prisma.TutorDetailsUpdateWithoutTutorInput, Prisma.TutorDetailsUncheckedUpdateWithoutTutorInput>
  create: Prisma.XOR<Prisma.TutorDetailsCreateWithoutTutorInput, Prisma.TutorDetailsUncheckedCreateWithoutTutorInput>
  where?: Prisma.TutorDetailsWhereInput
}

export type TutorDetailsUpdateToOneWithWhereWithoutTutorInput = {
  where?: Prisma.TutorDetailsWhereInput
  data: Prisma.XOR<Prisma.TutorDetailsUpdateWithoutTutorInput, Prisma.TutorDetailsUncheckedUpdateWithoutTutorInput>
}

export type TutorDetailsUpdateWithoutTutorInput = {
  date_of_birth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  emergency_contact_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergency_contact_mobile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_hourly_rate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bsb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_member_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  high_school?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  university_course?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  working_with_children?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  police_check?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  special_skills?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hsc_subjects?: Prisma.TutorDetailsUpdatehsc_subjectsInput | string[]
}

export type TutorDetailsUncheckedUpdateWithoutTutorInput = {
  date_of_birth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  emergency_contact_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergency_contact_mobile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_hourly_rate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  tfn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bsb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  account_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  super_member_number?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  high_school?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  university_course?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  working_with_children?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  police_check?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  special_skills?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hsc_subjects?: Prisma.TutorDetailsUpdatehsc_subjectsInput | string[]
}



export type TutorDetailsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tutor_id?: boolean
  date_of_birth?: boolean
  gender?: boolean
  address?: boolean
  job?: boolean
  start_date?: boolean
  end_date?: boolean
  emergency_contact_name?: boolean
  emergency_contact_mobile?: boolean
  start_hourly_rate?: boolean
  tfn?: boolean
  account_name?: boolean
  bsb?: boolean
  account_number?: boolean
  super_name?: boolean
  super_member_number?: boolean
  high_school?: boolean
  university_course?: boolean
  working_with_children?: boolean
  police_check?: boolean
  special_skills?: boolean
  hsc_subjects?: boolean
  tutor?: boolean | Prisma.TutorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tutorDetails"]>

export type TutorDetailsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tutor_id?: boolean
  date_of_birth?: boolean
  gender?: boolean
  address?: boolean
  job?: boolean
  start_date?: boolean
  end_date?: boolean
  emergency_contact_name?: boolean
  emergency_contact_mobile?: boolean
  start_hourly_rate?: boolean
  tfn?: boolean
  account_name?: boolean
  bsb?: boolean
  account_number?: boolean
  super_name?: boolean
  super_member_number?: boolean
  high_school?: boolean
  university_course?: boolean
  working_with_children?: boolean
  police_check?: boolean
  special_skills?: boolean
  hsc_subjects?: boolean
  tutor?: boolean | Prisma.TutorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tutorDetails"]>

export type TutorDetailsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tutor_id?: boolean
  date_of_birth?: boolean
  gender?: boolean
  address?: boolean
  job?: boolean
  start_date?: boolean
  end_date?: boolean
  emergency_contact_name?: boolean
  emergency_contact_mobile?: boolean
  start_hourly_rate?: boolean
  tfn?: boolean
  account_name?: boolean
  bsb?: boolean
  account_number?: boolean
  super_name?: boolean
  super_member_number?: boolean
  high_school?: boolean
  university_course?: boolean
  working_with_children?: boolean
  police_check?: boolean
  special_skills?: boolean
  hsc_subjects?: boolean
  tutor?: boolean | Prisma.TutorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tutorDetails"]>

export type TutorDetailsSelectScalar = {
  tutor_id?: boolean
  date_of_birth?: boolean
  gender?: boolean
  address?: boolean
  job?: boolean
  start_date?: boolean
  end_date?: boolean
  emergency_contact_name?: boolean
  emergency_contact_mobile?: boolean
  start_hourly_rate?: boolean
  tfn?: boolean
  account_name?: boolean
  bsb?: boolean
  account_number?: boolean
  super_name?: boolean
  super_member_number?: boolean
  high_school?: boolean
  university_course?: boolean
  working_with_children?: boolean
  police_check?: boolean
  special_skills?: boolean
  hsc_subjects?: boolean
}

export type TutorDetailsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"tutor_id" | "date_of_birth" | "gender" | "address" | "job" | "start_date" | "end_date" | "emergency_contact_name" | "emergency_contact_mobile" | "start_hourly_rate" | "tfn" | "account_name" | "bsb" | "account_number" | "super_name" | "super_member_number" | "high_school" | "university_course" | "working_with_children" | "police_check" | "special_skills" | "hsc_subjects", ExtArgs["result"]["tutorDetails"]>
export type TutorDetailsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tutor?: boolean | Prisma.TutorDefaultArgs<ExtArgs>
}
export type TutorDetailsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tutor?: boolean | Prisma.TutorDefaultArgs<ExtArgs>
}
export type TutorDetailsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tutor?: boolean | Prisma.TutorDefaultArgs<ExtArgs>
}

export type $TutorDetailsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TutorDetails"
  objects: {
    tutor: Prisma.$TutorPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    tutor_id: string
    date_of_birth: Date | null
    gender: string | null
    address: string | null
    job: string
    start_date: Date | null
    end_date: Date | null
    emergency_contact_name: string | null
    emergency_contact_mobile: string | null
    start_hourly_rate: runtime.Decimal | null
    tfn: string | null
    account_name: string | null
    bsb: string | null
    account_number: string | null
    super_name: string | null
    super_member_number: string | null
    high_school: string | null
    university_course: string | null
    working_with_children: string | null
    police_check: string | null
    special_skills: string | null
    hsc_subjects: string[]
  }, ExtArgs["result"]["tutorDetails"]>
  composites: {}
}

export type TutorDetailsGetPayload<S extends boolean | null | undefined | TutorDetailsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload, S>

export type TutorDetailsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TutorDetailsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TutorDetailsCountAggregateInputType | true
  }

export interface TutorDetailsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TutorDetails'], meta: { name: 'TutorDetails' } }
  /**
   * Find zero or one TutorDetails that matches the filter.
   * @param {TutorDetailsFindUniqueArgs} args - Arguments to find a TutorDetails
   * @example
   * // Get one TutorDetails
   * const tutorDetails = await prisma.tutorDetails.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TutorDetailsFindUniqueArgs>(args: Prisma.SelectSubset<T, TutorDetailsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TutorDetails that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TutorDetailsFindUniqueOrThrowArgs} args - Arguments to find a TutorDetails
   * @example
   * // Get one TutorDetails
   * const tutorDetails = await prisma.tutorDetails.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TutorDetailsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TutorDetailsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TutorDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorDetailsFindFirstArgs} args - Arguments to find a TutorDetails
   * @example
   * // Get one TutorDetails
   * const tutorDetails = await prisma.tutorDetails.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TutorDetailsFindFirstArgs>(args?: Prisma.SelectSubset<T, TutorDetailsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TutorDetails that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorDetailsFindFirstOrThrowArgs} args - Arguments to find a TutorDetails
   * @example
   * // Get one TutorDetails
   * const tutorDetails = await prisma.tutorDetails.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TutorDetailsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TutorDetailsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TutorDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorDetailsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TutorDetails
   * const tutorDetails = await prisma.tutorDetails.findMany()
   * 
   * // Get first 10 TutorDetails
   * const tutorDetails = await prisma.tutorDetails.findMany({ take: 10 })
   * 
   * // Only select the `tutor_id`
   * const tutorDetailsWithTutor_idOnly = await prisma.tutorDetails.findMany({ select: { tutor_id: true } })
   * 
   */
  findMany<T extends TutorDetailsFindManyArgs>(args?: Prisma.SelectSubset<T, TutorDetailsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TutorDetails.
   * @param {TutorDetailsCreateArgs} args - Arguments to create a TutorDetails.
   * @example
   * // Create one TutorDetails
   * const TutorDetails = await prisma.tutorDetails.create({
   *   data: {
   *     // ... data to create a TutorDetails
   *   }
   * })
   * 
   */
  create<T extends TutorDetailsCreateArgs>(args: Prisma.SelectSubset<T, TutorDetailsCreateArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TutorDetails.
   * @param {TutorDetailsCreateManyArgs} args - Arguments to create many TutorDetails.
   * @example
   * // Create many TutorDetails
   * const tutorDetails = await prisma.tutorDetails.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TutorDetailsCreateManyArgs>(args?: Prisma.SelectSubset<T, TutorDetailsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TutorDetails and returns the data saved in the database.
   * @param {TutorDetailsCreateManyAndReturnArgs} args - Arguments to create many TutorDetails.
   * @example
   * // Create many TutorDetails
   * const tutorDetails = await prisma.tutorDetails.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TutorDetails and only return the `tutor_id`
   * const tutorDetailsWithTutor_idOnly = await prisma.tutorDetails.createManyAndReturn({
   *   select: { tutor_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TutorDetailsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TutorDetailsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TutorDetails.
   * @param {TutorDetailsDeleteArgs} args - Arguments to delete one TutorDetails.
   * @example
   * // Delete one TutorDetails
   * const TutorDetails = await prisma.tutorDetails.delete({
   *   where: {
   *     // ... filter to delete one TutorDetails
   *   }
   * })
   * 
   */
  delete<T extends TutorDetailsDeleteArgs>(args: Prisma.SelectSubset<T, TutorDetailsDeleteArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TutorDetails.
   * @param {TutorDetailsUpdateArgs} args - Arguments to update one TutorDetails.
   * @example
   * // Update one TutorDetails
   * const tutorDetails = await prisma.tutorDetails.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TutorDetailsUpdateArgs>(args: Prisma.SelectSubset<T, TutorDetailsUpdateArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TutorDetails.
   * @param {TutorDetailsDeleteManyArgs} args - Arguments to filter TutorDetails to delete.
   * @example
   * // Delete a few TutorDetails
   * const { count } = await prisma.tutorDetails.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TutorDetailsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TutorDetailsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TutorDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorDetailsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TutorDetails
   * const tutorDetails = await prisma.tutorDetails.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TutorDetailsUpdateManyArgs>(args: Prisma.SelectSubset<T, TutorDetailsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TutorDetails and returns the data updated in the database.
   * @param {TutorDetailsUpdateManyAndReturnArgs} args - Arguments to update many TutorDetails.
   * @example
   * // Update many TutorDetails
   * const tutorDetails = await prisma.tutorDetails.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TutorDetails and only return the `tutor_id`
   * const tutorDetailsWithTutor_idOnly = await prisma.tutorDetails.updateManyAndReturn({
   *   select: { tutor_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TutorDetailsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TutorDetailsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TutorDetails.
   * @param {TutorDetailsUpsertArgs} args - Arguments to update or create a TutorDetails.
   * @example
   * // Update or create a TutorDetails
   * const tutorDetails = await prisma.tutorDetails.upsert({
   *   create: {
   *     // ... data to create a TutorDetails
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TutorDetails we want to update
   *   }
   * })
   */
  upsert<T extends TutorDetailsUpsertArgs>(args: Prisma.SelectSubset<T, TutorDetailsUpsertArgs<ExtArgs>>): Prisma.Prisma__TutorDetailsClient<runtime.Types.Result.GetResult<Prisma.$TutorDetailsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TutorDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorDetailsCountArgs} args - Arguments to filter TutorDetails to count.
   * @example
   * // Count the number of TutorDetails
   * const count = await prisma.tutorDetails.count({
   *   where: {
   *     // ... the filter for the TutorDetails we want to count
   *   }
   * })
  **/
  count<T extends TutorDetailsCountArgs>(
    args?: Prisma.Subset<T, TutorDetailsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TutorDetailsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TutorDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorDetailsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TutorDetailsAggregateArgs>(args: Prisma.Subset<T, TutorDetailsAggregateArgs>): Prisma.PrismaPromise<GetTutorDetailsAggregateType<T>>

  /**
   * Group by TutorDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorDetailsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TutorDetailsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TutorDetailsGroupByArgs['orderBy'] }
      : { orderBy?: TutorDetailsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TutorDetailsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTutorDetailsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TutorDetails model
 */
readonly fields: TutorDetailsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TutorDetails.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TutorDetailsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tutor<T extends Prisma.TutorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TutorDefaultArgs<ExtArgs>>): Prisma.Prisma__TutorClient<runtime.Types.Result.GetResult<Prisma.$TutorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TutorDetails model
 */
export interface TutorDetailsFieldRefs {
  readonly tutor_id: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly date_of_birth: Prisma.FieldRef<"TutorDetails", 'DateTime'>
  readonly gender: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly address: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly job: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly start_date: Prisma.FieldRef<"TutorDetails", 'DateTime'>
  readonly end_date: Prisma.FieldRef<"TutorDetails", 'DateTime'>
  readonly emergency_contact_name: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly emergency_contact_mobile: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly start_hourly_rate: Prisma.FieldRef<"TutorDetails", 'Decimal'>
  readonly tfn: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly account_name: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly bsb: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly account_number: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly super_name: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly super_member_number: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly high_school: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly university_course: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly working_with_children: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly police_check: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly special_skills: Prisma.FieldRef<"TutorDetails", 'String'>
  readonly hsc_subjects: Prisma.FieldRef<"TutorDetails", 'String[]'>
}
    

// Custom InputTypes
/**
 * TutorDetails findUnique
 */
export type TutorDetailsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * Filter, which TutorDetails to fetch.
   */
  where: Prisma.TutorDetailsWhereUniqueInput
}

/**
 * TutorDetails findUniqueOrThrow
 */
export type TutorDetailsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * Filter, which TutorDetails to fetch.
   */
  where: Prisma.TutorDetailsWhereUniqueInput
}

/**
 * TutorDetails findFirst
 */
export type TutorDetailsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * Filter, which TutorDetails to fetch.
   */
  where?: Prisma.TutorDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorDetails to fetch.
   */
  orderBy?: Prisma.TutorDetailsOrderByWithRelationInput | Prisma.TutorDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TutorDetails.
   */
  cursor?: Prisma.TutorDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TutorDetails.
   */
  distinct?: Prisma.TutorDetailsScalarFieldEnum | Prisma.TutorDetailsScalarFieldEnum[]
}

/**
 * TutorDetails findFirstOrThrow
 */
export type TutorDetailsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * Filter, which TutorDetails to fetch.
   */
  where?: Prisma.TutorDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorDetails to fetch.
   */
  orderBy?: Prisma.TutorDetailsOrderByWithRelationInput | Prisma.TutorDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TutorDetails.
   */
  cursor?: Prisma.TutorDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TutorDetails.
   */
  distinct?: Prisma.TutorDetailsScalarFieldEnum | Prisma.TutorDetailsScalarFieldEnum[]
}

/**
 * TutorDetails findMany
 */
export type TutorDetailsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * Filter, which TutorDetails to fetch.
   */
  where?: Prisma.TutorDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorDetails to fetch.
   */
  orderBy?: Prisma.TutorDetailsOrderByWithRelationInput | Prisma.TutorDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TutorDetails.
   */
  cursor?: Prisma.TutorDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorDetails.
   */
  skip?: number
  distinct?: Prisma.TutorDetailsScalarFieldEnum | Prisma.TutorDetailsScalarFieldEnum[]
}

/**
 * TutorDetails create
 */
export type TutorDetailsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * The data needed to create a TutorDetails.
   */
  data: Prisma.XOR<Prisma.TutorDetailsCreateInput, Prisma.TutorDetailsUncheckedCreateInput>
}

/**
 * TutorDetails createMany
 */
export type TutorDetailsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TutorDetails.
   */
  data: Prisma.TutorDetailsCreateManyInput | Prisma.TutorDetailsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TutorDetails createManyAndReturn
 */
export type TutorDetailsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * The data used to create many TutorDetails.
   */
  data: Prisma.TutorDetailsCreateManyInput | Prisma.TutorDetailsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TutorDetails update
 */
export type TutorDetailsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * The data needed to update a TutorDetails.
   */
  data: Prisma.XOR<Prisma.TutorDetailsUpdateInput, Prisma.TutorDetailsUncheckedUpdateInput>
  /**
   * Choose, which TutorDetails to update.
   */
  where: Prisma.TutorDetailsWhereUniqueInput
}

/**
 * TutorDetails updateMany
 */
export type TutorDetailsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TutorDetails.
   */
  data: Prisma.XOR<Prisma.TutorDetailsUpdateManyMutationInput, Prisma.TutorDetailsUncheckedUpdateManyInput>
  /**
   * Filter which TutorDetails to update
   */
  where?: Prisma.TutorDetailsWhereInput
  /**
   * Limit how many TutorDetails to update.
   */
  limit?: number
}

/**
 * TutorDetails updateManyAndReturn
 */
export type TutorDetailsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * The data used to update TutorDetails.
   */
  data: Prisma.XOR<Prisma.TutorDetailsUpdateManyMutationInput, Prisma.TutorDetailsUncheckedUpdateManyInput>
  /**
   * Filter which TutorDetails to update
   */
  where?: Prisma.TutorDetailsWhereInput
  /**
   * Limit how many TutorDetails to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TutorDetails upsert
 */
export type TutorDetailsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * The filter to search for the TutorDetails to update in case it exists.
   */
  where: Prisma.TutorDetailsWhereUniqueInput
  /**
   * In case the TutorDetails found by the `where` argument doesn't exist, create a new TutorDetails with this data.
   */
  create: Prisma.XOR<Prisma.TutorDetailsCreateInput, Prisma.TutorDetailsUncheckedCreateInput>
  /**
   * In case the TutorDetails was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TutorDetailsUpdateInput, Prisma.TutorDetailsUncheckedUpdateInput>
}

/**
 * TutorDetails delete
 */
export type TutorDetailsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
  /**
   * Filter which TutorDetails to delete.
   */
  where: Prisma.TutorDetailsWhereUniqueInput
}

/**
 * TutorDetails deleteMany
 */
export type TutorDetailsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TutorDetails to delete
   */
  where?: Prisma.TutorDetailsWhereInput
  /**
   * Limit how many TutorDetails to delete.
   */
  limit?: number
}

/**
 * TutorDetails without action
 */
export type TutorDetailsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorDetails
   */
  select?: Prisma.TutorDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorDetails
   */
  omit?: Prisma.TutorDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorDetailsInclude<ExtArgs> | null
}
