
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Student.ts'
export type * from './models/Parent.ts'
export type * from './models/StudentParent.ts'
export type * from './models/Tutor.ts'
export type * from './models/ClassTime.ts'
export type * from './models/Subject.ts'
export type * from './models/Grade.ts'
export type * from './models/SubjectOffering.ts'
export type * from './models/Term.ts'
export type * from './models/Enrolment.ts'
export type * from './models/Attendance.ts'
export type * from './models/Payment.ts'
export type * from './commonInputTypes.ts'