
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Student: 'Student',
  Parent: 'Parent',
  StudentParent: 'StudentParent',
  Tutor: 'Tutor',
  ClassTime: 'ClassTime',
  Subject: 'Subject',
  Grade: 'Grade',
  SubjectOffering: 'SubjectOffering',
  Term: 'Term',
  Enrolment: 'Enrolment',
  Attendance: 'Attendance',
  Payment: 'Payment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const StudentScalarFieldEnum = {
  student_id: 'student_id',
  student_mobile: 'student_mobile',
  first_name: 'first_name',
  last_name: 'last_name',
  preferred_name: 'preferred_name',
  grade_at_school: 'grade_at_school',
  school: 'school',
  suburb_of_home: 'suburb_of_home',
  email: 'email',
  location: 'location',
  gender: 'gender',
  status: 'status',
  notes: 'notes'
} as const

export type StudentScalarFieldEnum = (typeof StudentScalarFieldEnum)[keyof typeof StudentScalarFieldEnum]


export const ParentScalarFieldEnum = {
  parent_id: 'parent_id',
  parent_mobile: 'parent_mobile',
  first_name: 'first_name',
  last_name: 'last_name',
  email: 'email',
  notes: 'notes'
} as const

export type ParentScalarFieldEnum = (typeof ParentScalarFieldEnum)[keyof typeof ParentScalarFieldEnum]


export const StudentParentScalarFieldEnum = {
  student_parent_id: 'student_parent_id',
  student_id: 'student_id',
  parent_id: 'parent_id',
  relationship: 'relationship'
} as const

export type StudentParentScalarFieldEnum = (typeof StudentParentScalarFieldEnum)[keyof typeof StudentParentScalarFieldEnum]


export const TutorScalarFieldEnum = {
  tutor_id: 'tutor_id',
  first_name: 'first_name',
  last_name: 'last_name',
  phone: 'phone',
  email: 'email'
} as const

export type TutorScalarFieldEnum = (typeof TutorScalarFieldEnum)[keyof typeof TutorScalarFieldEnum]


export const ClassTimeScalarFieldEnum = {
  class_id: 'class_id',
  offering_id: 'offering_id',
  tutor_id: 'tutor_id',
  day_of_week: 'day_of_week',
  start_time: 'start_time',
  end_time: 'end_time',
  capacity: 'capacity',
  active: 'active'
} as const

export type ClassTimeScalarFieldEnum = (typeof ClassTimeScalarFieldEnum)[keyof typeof ClassTimeScalarFieldEnum]


export const SubjectScalarFieldEnum = {
  subject_id: 'subject_id',
  name: 'name'
} as const

export type SubjectScalarFieldEnum = (typeof SubjectScalarFieldEnum)[keyof typeof SubjectScalarFieldEnum]


export const GradeScalarFieldEnum = {
  grade_id: 'grade_id',
  label: 'label',
  school_year_number: 'school_year_number'
} as const

export type GradeScalarFieldEnum = (typeof GradeScalarFieldEnum)[keyof typeof GradeScalarFieldEnum]


export const SubjectOfferingScalarFieldEnum = {
  offering_id: 'offering_id',
  subject_id: 'subject_id',
  grade_id: 'grade_id',
  location: 'location',
  price_per_term: 'price_per_term'
} as const

export type SubjectOfferingScalarFieldEnum = (typeof SubjectOfferingScalarFieldEnum)[keyof typeof SubjectOfferingScalarFieldEnum]


export const TermScalarFieldEnum = {
  term_id: 'term_id',
  name: 'name',
  year: 'year',
  start_date: 'start_date',
  end_date: 'end_date'
} as const

export type TermScalarFieldEnum = (typeof TermScalarFieldEnum)[keyof typeof TermScalarFieldEnum]


export const EnrolmentScalarFieldEnum = {
  enrolment_id: 'enrolment_id',
  student_id: 'student_id',
  class_id: 'class_id',
  term_id: 'term_id',
  enrolment_date: 'enrolment_date',
  status: 'status'
} as const

export type EnrolmentScalarFieldEnum = (typeof EnrolmentScalarFieldEnum)[keyof typeof EnrolmentScalarFieldEnum]


export const AttendanceScalarFieldEnum = {
  attendance_id: 'attendance_id',
  student_id: 'student_id',
  class_id: 'class_id',
  week: 'week',
  status: 'status',
  notes: 'notes'
} as const

export type AttendanceScalarFieldEnum = (typeof AttendanceScalarFieldEnum)[keyof typeof AttendanceScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  payment_id: 'payment_id',
  enrolment_id: 'enrolment_id',
  amount_due: 'amount_due',
  amount_paid: 'amount_paid',
  payment_date: 'payment_date',
  payment_type: 'payment_type',
  status: 'status',
  receipt: 'receipt',
  notes: 'notes'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

